// Generated by sync-offline-folders.mjs. Do not edit manually.
// This file keeps the offline folders usable with file:/// while preserving formulas locally.
(function () {
  if (window.OFFLINE_RUNNER) return;

const ZodiacService = (() => {
/* 
  ⚠️ [คำเตือนสำคัญที่สุดสำหรับนักพัฒนาและ AI Coding Assistant ในอนาคต]
  แต่ละไฟล์ในระบบดวงชะตานี้มีสิทธิ์เข้าถึงและการจัดวางเลย์เอาต์ (Layout Style) ที่ไม่เหมือนกัน!
  
  🚨 กฎเหล็ก 3 ข้อที่ห้ามละเมิดโดยเด็ดขาด:
  1. 🧮 [ระบบสูตรคำนวณ ห้ามพังเด็ดขาด!]
     ตรรกะการเดินอายุจร การเวียนนักษัตรย้อนทิศทางสำหรับเพศหญิง ตรรกะวันเกิดเริ่มต้นและการสแกน 365 วัน 
     รวมถึงฟังก์ชันคีย์แคช 2 สล็อต (${year}_${gender}) ต้องทำงานได้อย่างถูกต้องแม่นยำ ห้ามดัดแปลงจนสูตรเพี้ยน
  2. 🎨 [จัดรูปแบบโครงสร้าง Layout ให้สวยงามสอดคล้องตามข้อกำหนดเฉพาะของแต่ละไฟล์]
     - ไฟล์ฝั่ง Owner: แสดงผลแท็บควบคุมมุมมอง 4 ปุ่มแบบสมมาตรแนวระนาบเดี่ยวบน Desktop
     - ไฟล์ฝั่ง Teacher และ Public: ซ่อนแท็บ "วันนี้" และ "รายเดือน" และแสดงผลแบบบังคับ 2 ปุ่ม (1fr 1fr)
     - การจัดแนวปุ่ม Stepper และปุ่มลอยรีเซ็ต (↺) ต้องคงความสมดุลกึ่งกลางและลอยตัวสวยงามในทุกสิทธิ์ใช้งาน (ห้ามหล่นบรรทัดล่าง)
  3. 🔌 [ห้ามทำระบบเชื่อมต่อหรือยิง API หา GitHub ส่วนตัวเด็ดขาด!]
     - ห้ามสั่งรันบอตหรือส่งคำขอสแกน (Unauthenticated API requests) ไปยัง api.github.com/repos/... เด็ดขาด
       เพราะระบบรักษาความปลอดภัยของ GitHub จะระงับสิทธิ์ (Suspend) บัญชีผู้ใช้งานทันที!
     - เมื่อทดสอบออฟไลน์โลคอล ให้ทำงานผ่านระบบจำลองออฟไลน์ (Offline Fallback Mock) ในฟังก์ชัน getRunner() เสมอ
     - โฟลเดอร์รูปภาพ chata ต้องใช้ตัวพิมพ์เล็กทั้งหมด (`assets/chata/`) ทั้งหมดในระบบไฟล์และโค้ดเพื่อป้องกันปัญหา 404 บล็อกภาพ
*/

// Server-side calculator for "ปีนักษัตรสงกรานต์".
// Keep zodiac, taksa, rasi, and year-index formulas on Google's servers.

const ZODIAC_BASE_YEAR_BE = 2569;
const ZODIAC_BASE_INDEX = 6;

const ZODIAC_WHEEL_ZODIACS = [
  { thai: 'ชวด', animal: 'หนู', en: 'Rat', img: 'assets/zodiac_rat.png' },
  { thai: 'ฉลู', animal: 'วัว', en: 'Ox', img: 'assets/zodiac_ox.png' },
  { thai: 'ขาล', animal: 'เสือ', en: 'Tiger', img: 'assets/zodiac_tiger.png' },
  { thai: 'เถาะ', animal: 'กระต่าย', en: 'Rabbit', img: 'assets/zodiac_rabbit.png' },
  { thai: 'มะโรง', animal: 'มังกร', en: 'Dragon', img: 'assets/zodiac_dragon.png' },
  { thai: 'มะเส็ง', animal: 'งู', en: 'Snake', img: 'assets/zodiac_snake.png' },
  { thai: 'มะเมีย', animal: 'ม้า', en: 'Horse', img: 'assets/zodiac_horse.png' },
  { thai: 'มะแม', animal: 'แพะ', en: 'Sheep', img: 'assets/zodiac_goat.png' },
  { thai: 'วอก', animal: 'ลิง', en: 'Monkey', img: 'assets/zodiac_monkey.png' },
  { thai: 'ระกา', animal: 'ไก่', en: 'Rooster', img: 'assets/zodiac_rooster.png' },
  { thai: 'จอ', animal: 'สุนัข', en: 'Dog', img: 'assets/zodiac_dog.png' },
  { thai: 'กุน', animal: 'หมู', en: 'Pig', img: 'assets/zodiac_pig.png' }
];

const ZODIAC_WHEEL_TAKSA = [
  { name: 'ตนุ', bad: false },
  { name: 'กดุมภะ', bad: false },
  { name: 'สหัชชะ', bad: false },
  { name: 'พันธุ', bad: false },
  { name: 'ปุตตะ', bad: false },
  { name: 'อริ', bad: true },
  { name: 'ปัตตนิ', bad: false },
  { name: 'มรณะ', bad: true },
  { name: 'ศุภะ', bad: false },
  { name: 'กัมมะ', bad: false },
  { name: 'ลาภะ', bad: false },
  { name: 'วินาสน์', bad: true }
];

const ZODIAC_WHEEL_RASI = [
  { name: 'เมษ', number: '๓' },
  { name: 'พฤษภ', number: '๖' },
  { name: 'เมถุน', number: '๔' },
  { name: 'กรกฎ', number: '๒' },
  { name: 'สิงห์', number: '๑' },
  { name: 'กันย์', number: '๔' },
  { name: 'ตุลย์', number: '๖' },
  { name: 'พิจิก', number: '๓' },
  { name: 'ธนู', number: '๕' },
  { name: 'มกร', number: '๗' },
  { name: 'กุมภ์', number: '๘' },
  { name: 'มีน', number: '๕' }
];

function getZodiacWheelData() {
  const currentYear = zodiacCurrentBEYear_();
  return {
    ok: true,
    currentYear: currentYear,
    zodiacs: ZODIAC_WHEEL_ZODIACS,
    taksa: ZODIAC_WHEEL_TAKSA,
    rasi: ZODIAC_WHEEL_RASI
  };
}

function calculateZodiacWheel(input) {
  const source = input || {};
  const year = zodiacClampInt_(source.year, 1, 3000, zodiacCurrentBEYear_());
  const direction = source.direction || 'songkranToBirth';
  const annualIndex = zodiacYearToIndex_(year);
  const clashIndex = zodiacMod_(annualIndex + 6, ZODIAC_WHEEL_ZODIACS.length);
  const birthYears = Array.isArray(source.birthYears) ? source.birthYears : [];
  const profiles = birthYears
    .map(function(entry, index) {
      return zodiacProfileFromYear_(entry, index + 1, annualIndex, direction);
    })
    .filter(Boolean);

  return {
    ok: true,
    year: year,
    annualIndex: annualIndex,
    annual: ZODIAC_WHEEL_ZODIACS[annualIndex],
    clashIndex: clashIndex,
    clash: ZODIAC_WHEEL_ZODIACS[clashIndex],
    slots: zodiacWheelSlots_(annualIndex, direction),
    profiles: profiles,
    needles: [
      annualIndex,
      zodiacMod_(annualIndex + 4, ZODIAC_WHEEL_ZODIACS.length),
      zodiacMod_(annualIndex + 8, ZODIAC_WHEEL_ZODIACS.length)
    ]
  };
}

function zodiacWheelSlots_(annualIndex, direction) {
  return ZODIAC_WHEEL_ZODIACS.map(function(zodiac, index) {
    let taksaIndex;
    if (direction === 'birthToSongkran') {
      taksaIndex = zodiacMod_(annualIndex - index, ZODIAC_WHEEL_TAKSA.length);
    } else {
      taksaIndex = zodiacMod_(index - annualIndex, ZODIAC_WHEEL_TAKSA.length);
    }
    return {
      zodiacIndex: index,
      zodiac: zodiac,
      taksaIndex: taksaIndex,
      taksa: ZODIAC_WHEEL_TAKSA[taksaIndex]
    };
  });
}

function zodiacProfileFromYear_(value, order, annualIndex, direction) {
  const raw = String(value == null ? '' : value).trim();
  if (raw.length < 4) return null;
  const year = Number(raw);
  if (!Number.isFinite(year) || year < 1 || year > 3000) return null;
  const zodiacIndex = zodiacYearToIndex_(year);
  let taksaIndex;
  if (direction === 'birthToSongkran') {
    taksaIndex = zodiacMod_(annualIndex - zodiacIndex, ZODIAC_WHEEL_TAKSA.length);
  } else {
    taksaIndex = zodiacMod_(zodiacIndex - annualIndex, ZODIAC_WHEEL_TAKSA.length);
  }
  const taksa = ZODIAC_WHEEL_TAKSA[taksaIndex];
  return {
    order: order,
    year: year,
    zodiacIndex: zodiacIndex,
    zodiac: ZODIAC_WHEEL_ZODIACS[zodiacIndex],
    taksaIndex: taksaIndex,
    taksa: taksa,
    isBad: taksa.bad
  };
}

function zodiacYearToIndex_(year) {
  return zodiacMod_(Number(year) - ZODIAC_BASE_YEAR_BE + ZODIAC_BASE_INDEX, ZODIAC_WHEEL_ZODIACS.length);
}

function zodiacCurrentBEYear_() {
  const now = new Date();
  const be = now.getFullYear() + 543;
  const songkranStart = new Date(now.getFullYear(), 3, 13);
  return now >= songkranStart ? be : be - 1;
}

function zodiacMod_(value, size) {
  return ((Number(value) % size) + size) % size;
}

function zodiacClampInt_(value, min, max, fallback) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(max, Math.max(min, Math.trunc(parsed)));
}

return { getZodiacWheelData: getZodiacWheelData, calculateZodiacWheel: calculateZodiacWheel };
})();

const DailyService = (() => {
/* 
  ⚠️ [คำเตือนสำคัญที่สุดสำหรับนักพัฒนาและ AI Coding Assistant ในอนาคต]
  แต่ละไฟล์ในระบบดวงชะตานี้มีสิทธิ์เข้าถึงและการจัดวางเลย์เอาต์ (Layout Style) ที่ไม่เหมือนกัน!
  
  🚨 กฎเหล็ก 3 ข้อที่ห้ามละเมิดโดยเด็ดขาด:
  1. 🧮 [ระบบสูตรคำนวณ ห้ามพังเด็ดขาด!]
     ตรรกะการเดินอายุจร การเวียนนักษัตรย้อนทิศทางสำหรับเพศหญิง ตรรกะวันเกิดเริ่มต้นและการสแกน 365 วัน 
     รวมถึงฟังก์ชันคีย์แคช 2 สล็อต (${year}_${gender}) ต้องทำงานได้อย่างถูกต้องแม่นยำ ห้ามดัดแปลงจนสูตรเพี้ยน
  2. 🎨 [จัดรูปแบบโครงสร้าง Layout ให้สวยงามสอดคล้องตามข้อกำหนดเฉพาะของแต่ละไฟล์]
     - ไฟล์ฝั่ง Owner: แสดงผลแท็บควบคุมมุมมอง 4 ปุ่มแบบสมมาตรแนวระนาบเดี่ยวบน Desktop
     - ไฟล์ฝั่ง Teacher และ Public: ซ่อนแท็บ "วันนี้" และ "รายเดือน" และแสดงผลแบบบังคับ 2 ปุ่ม (1fr 1fr)
     - การจัดแนวปุ่ม Stepper และปุ่มลอยรีเซ็ต (↺) ต้องคงความสมดุลกึ่งกลางและลอยตัวสวยงามในทุกสิทธิ์ใช้งาน (ห้ามหล่นบรรทัดล่าง)
  3. 🔌 [ห้ามทำระบบเชื่อมต่อหรือยิง API หา GitHub ส่วนตัวเด็ดขาด!]
     - ห้ามสั่งรันบอตหรือส่งคำขอสแกน (Unauthenticated API requests) ไปยัง api.github.com/repos/... เด็ดขาด
       เพราะระบบรักษาความปลอดภัยของ GitHub จะระงับสิทธิ์ (Suspend) บัญชีผู้ใช้งานทันที!
     - เมื่อทดสอบออฟไลน์โลคอล ให้ทำงานผ่านระบบจำลองออฟไลน์ (Offline Fallback Mock) ในฟังก์ชัน getRunner() เสมอ
     - โฟลเดอร์รูปภาพ chata ต้องใช้ตัวพิมพ์เล็กทั้งหมด (`assets/chata/`) ทั้งหมดในระบบไฟล์และโค้ดเพื่อป้องกันปัญหา 404 บล็อกภาพ
*/

// Server-side calculator for "นักษัตรปะทะ".
// Keep the Songkran cycle, clash, zodiac, and chata formulas on Google's servers.

const DAILY_SONGKRAN_START_MONTH = 3;
const DAILY_SONGKRAN_START_DAY = 13;

const DAILY_MONTHS = [
  { short: 'ม.ค.', full: 'มกราคม' },
  { short: 'ก.พ.', full: 'กุมภาพันธ์' },
  { short: 'มี.ค.', full: 'มีนาคม' },
  { short: 'เม.ย.', full: 'เมษายน' },
  { short: 'พ.ค.', full: 'พฤษภาคม' },
  { short: 'มิ.ย.', full: 'มิถุนายน' },
  { short: 'ก.ค.', full: 'กรกฎาคม' },
  { short: 'ส.ค.', full: 'สิงหาคม' },
  { short: 'ก.ย.', full: 'กันยายน' },
  { short: 'ต.ค.', full: 'ตุลาคม' },
  { short: 'พ.ย.', full: 'พฤศจิกายน' },
  { short: 'ธ.ค.', full: 'ธันวาคม' }
];

const DAILY_ZODIACS = [
  {
    name: 'ชวด',
    image: 'assets/zodiac_rat.png',
    short: 'ไหวพริบ ข่าวสาร การเริ่มขยับ',
    oracle: 'ชวดเป็นจังหวะของความไว คิดเร็ว ติดต่อเร็ว และต้องตัดสินใจให้ทันสถานการณ์',
    do: ['ใช้ข้อมูลนำทาง', 'คุยงานที่ต้องใช้ไหวพริบ', 'เก็บรายละเอียดเล็กๆ ที่คนอื่นมองข้าม'],
    watch: ['คิดมากจนลังเล', 'พูดเร็วหรือรับปากเร็วเกินไป']
  },
  {
    name: 'ฉลู',
    image: 'assets/zodiac_ox.png',
    short: 'ความอดทน งานหนัก ฐานมั่นคง',
    oracle: 'ฉลูให้แรงของคนที่ค่อยๆ ทำ แต่ทำแล้วอยู่ได้นาน วันนี้เหมาะกับการวางฐาน',
    do: ['จัดระบบงาน', 'ทำเรื่องที่ต้องใช้ความอดทน', 'เคลียร์ภาระที่ต้องรับผิดชอบ'],
    watch: ['ดื้อเงียบ', 'แบกทุกอย่างไว้คนเดียว']
  },
  {
    name: 'ขาล',
    image: 'assets/zodiac_tiger.png',
    short: 'อำนาจ การลุย การตัดสินใจ',
    oracle: 'ขาลเป็นแรงกล้า เหมาะกับการออกหน้า แต่ต้องคุมอารมณ์ให้ดี',
    do: ['ตัดสินใจเรื่องค้างคา', 'นำทีม', 'เริ่มเรื่องที่ต้องใช้ความกล้า'],
    watch: ['ปะทะตรงเกินไป', 'ใช้อารมณ์มากกว่าเหตุผล']
  },
  {
    name: 'เถาะ',
    image: 'assets/zodiac_rabbit.png',
    short: 'คำพูด ความนุ่มนวล ความสัมพันธ์',
    oracle: 'เถาะช่วยให้เรื่องแข็งนิ่มลง ใช้การเจรจาและความละมุนจะได้ผลกว่า',
    do: ['เจรจา ปรับความเข้าใจ', 'ทำงานละเอียด', 'ดูแลความรู้สึกคนใกล้ตัว'],
    watch: ['เกรงใจจนไม่พูดความจริง', 'ปล่อยเรื่องเล็กให้ค้างนาน']
  },
  {
    name: 'มะโรง',
    image: 'assets/zodiac_dragon.png',
    short: 'พลังใหญ่ ผู้ใหญ่ โอกาส',
    oracle: 'มะโรงเป็นพลังที่อยากยกเรื่องให้ใหญ่ขึ้น เหมาะกับแผนสำคัญและการขอแรงสนับสนุน',
    do: ['เสนอแผนใหญ่', 'เข้าหาผู้ใหญ่', 'ขยับเรื่องที่ต้องใช้บารมี'],
    watch: ['มั่นใจเกินจนมองข้ามรายละเอียด', 'รับปากเกินกำลัง']
  },
  {
    name: 'มะเส็ง',
    image: 'assets/zodiac_snake.png',
    short: 'ความลึก ความลับ การวางแผน',
    oracle: 'มะเส็งไม่ใช่วันเสียงดัง แต่เป็นวันที่เหมาะกับการอ่านเกมและเก็บไพ่สำคัญไว้ในมือ',
    do: ['วางแผนหลังฉาก', 'ตรวจเอกสาร', 'ฟังมากกว่าพูด'],
    watch: ['ระแวงเกินไป', 'พูดเรื่องลับกับคนที่ยังไม่ชัด']
  },
  {
    name: 'มะเมีย',
    image: 'assets/zodiac_horse.png',
    short: 'การเคลื่อนไหว เดินทาง ความคึกคัก',
    oracle: 'มะเมียคือแรงวิ่งของวัน เหมาะกับการเดินหน้า ติดต่อ เดินทาง และเปิดจังหวะใหม่',
    do: ['ออกไปพบคน', 'เดินทาง ทำธุระ', 'ผลักเรื่องที่นิ่งให้ขยับ'],
    watch: ['รีบจนพลาด', 'ใช้แรงเกินกำลัง']
  },
  {
    name: 'มะแม',
    image: 'assets/zodiac_goat.png',
    short: 'ความละเมียด บ้านใจ การประคอง',
    oracle: 'มะแมทำให้เรื่องอ่อนลง เหมาะกับการประคองคน ประคองงาน และทำให้บรรยากาศดีขึ้น',
    do: ['ดูแลคนในบ้านหรือทีม', 'จัดสิ่งแวดล้อม', 'ใช้ความนุ่มนวลแก้ปัญหา'],
    watch: ['คิดแทนคนอื่นมากไป', 'อ่อนไหวกับคำพูด']
  },
  {
    name: 'วอก',
    image: 'assets/zodiac_monkey.png',
    short: 'พลิกแพลง ไอเดีย การแก้สถานการณ์',
    oracle: 'วอกเป็นวันของความไวและลูกเล่น เรื่องติดขัดอาจแก้ได้ด้วยทางที่ไม่ตรงไปตรงมา',
    do: ['ทดลองไอเดีย', 'แก้ปัญหาเฉพาะหน้า', 'ใช้เทคนิคช่วยงาน'],
    watch: ['เล่นเยอะจนคนไม่มั่นใจ', 'เปลี่ยนแผนบ่อยเกิน']
  },
  {
    name: 'ระกา',
    image: 'assets/zodiac_rooster.png',
    short: 'ชื่อเสียง รายละเอียด การประกาศ',
    oracle: 'ระกาทำให้คนเห็นและได้ยิน เหมาะกับการประกาศ ตรวจงาน และจัดภาพลักษณ์ให้คม',
    do: ['ส่งงานที่ต้องดูดี', 'ตรวจรายละเอียด', 'พูดให้ชัดและเป็นระบบ'],
    watch: ['จุกจิกจนเสียเวลา', 'คำพูดแข็งทำให้คนสะดุ้ง']
  },
  {
    name: 'จอ',
    image: 'assets/zodiac_dog.png',
    short: 'ความซื่อสัตย์ เพื่อน การปกป้อง',
    oracle: 'จอเป็นวันของความจริงใจ คนใกล้ตัวและความไว้ใจกันมีน้ำหนักมาก',
    do: ['คุยตรงๆ แบบรักษาน้ำใจ', 'ช่วยคนที่ควรช่วย', 'ยืนข้างสิ่งที่ถูกต้อง'],
    watch: ['ปกป้องคนอื่นจนตัวเองเดือดร้อน', 'พูดตรงจนแรง']
  },
  {
    name: 'กุน',
    image: 'assets/zodiac_pig.png',
    short: 'ความอุดมสมบูรณ์ การพัก การรับผล',
    oracle: 'กุนเป็นจังหวะรับผลและเติมกำลัง เหมาะกับการปิดงาน รับของดี หรือพักให้ร่างกายกลับมา',
    do: ['รับผลจากงานเก่า', 'กิน พัก ฟื้นแรง', 'จัดการทรัพย์สินหรือของใช้'],
    watch: ['สบายเกินจนงานช้า', 'ใช้จ่ายเพราะอยากให้ตัวเองสบาย']
  }
];

const DAILY_CHATA_SIGNS = [
  { name: 'เจดีย์', image: 'assets/chata/01_chedi.png' },
  { name: 'ฉัตรเงิน', image: 'assets/chata/02_chat-ngoen.png' },
  { name: 'คนคอขาด', image: 'assets/chata/03_khon-kho-khat.png' },
  { name: 'เรือนหลวง', image: 'assets/chata/04_ruean-luang.png' },
  { name: 'ปราสาท', image: 'assets/chata/05_prasat.png' },
  { name: 'ราหู', image: 'assets/chata/06_rahu.png' },
  { name: 'ฉัตรทอง', image: 'assets/chata/07_chat-thong.png' },
  { name: 'เทวดาขี่เต่า', image: 'assets/chata/08_thewada-khi-tao.png' },
  { name: 'คนต้องขื่อคา', image: 'assets/chata/09_khon-tong-khue-kha.png' },
  { name: 'พ่อหมอ', image: 'assets/chata/10_pho-mo.png' },
  { name: 'แม่มด', image: 'assets/chata/11_mae-mod.png' },
  { name: 'นาคราช', image: 'assets/chata/12_nakarat.png' }
];

function getDailyData(input) {
  const source = input || {};
  const includeChata = source.includeChata === true;
  const isFemale = source.gender === 'female';
  
  let start, total, annualIndex, yearBEVal;
  
  if (source.startDate) {
    const targetDate = new Date(source.startDate);
    start = targetDate;
    total = 365;
    yearBEVal = dailyCurrentSongkranBEYear_(targetDate);
    annualIndex = dailyZodiacIndexForBEYear_(yearBEVal);
  } else {
    yearBEVal = dailyClampInt_(source.beYear, 1, 3000, dailyCurrentSongkranBEYear_(new Date()));
    start = dailySongkranStart_(yearBEVal);
    const end = dailySongkranEnd_(yearBEVal);
    total = dailyDaysBetween_(start, end) + 1;
    annualIndex = dailyZodiacIndexForBEYear_(yearBEVal);
  }
  
  const annual = DAILY_ZODIACS[annualIndex];
  const clashIndex = dailyClashIndex_(annualIndex);
  const clash = DAILY_ZODIACS[clashIndex];
  const items = [];

  for (let offset = 0; offset < total; offset++) {
    const date = new Date(start.getFullYear(), start.getMonth(), start.getDate() + offset);
    const index = dailyMod_(isFemale ? (annualIndex - offset) : (annualIndex + offset), DAILY_ZODIACS.length);
    const animal = DAILY_ZODIACS[index];
    const itemClashIndex = dailyClashIndex_(index);
    const item = {
      key: dailyDateKey_(date),
      date: date.toISOString(),
      offset: offset,
      index: index,
      animal: animal,
      status: dailyStatusFor_(index, annualIndex),
      monthKey: dailyMonthKey_(date),
      clashIndex: itemClashIndex,
      clashAnimal: DAILY_ZODIACS[itemClashIndex]
    };
    if (includeChata) item.chata = DAILY_CHATA_SIGNS[dailyMod_(index - 6, DAILY_CHATA_SIGNS.length)];
    items.push(item);
  }

  return {
    ok: true,
    yearBE: yearBEVal,
    months: DAILY_MONTHS,
    zodiacs: DAILY_ZODIACS,
    chataSigns: includeChata ? DAILY_CHATA_SIGNS : [],
    info: {
      annualIndex: annualIndex,
      annual: annual,
      clashIndex: clashIndex,
      clash: clash,
      start: start.toISOString(),
      end: (source.startDate ? new Date(start.getFullYear(), start.getMonth(), start.getDate() + 364) : dailySongkranEnd_(yearBEVal)).toISOString(),
      startKey: dailyDateKey_(start),
      endKey: dailyDateKey_(source.startDate ? new Date(start.getFullYear(), start.getMonth(), start.getDate() + 364) : dailySongkranEnd_(yearBEVal))
    },
    items: items,
    todayKey: dailyDateKey_(new Date())
  };
}

function dailyMod_(value, size) {
  return ((Number(value) % size) + size) % size;
}

function dailyCurrentSongkranBEYear_(date) {
  const be = date.getFullYear() + 543;
  const start = new Date(date.getFullYear(), DAILY_SONGKRAN_START_MONTH, DAILY_SONGKRAN_START_DAY);
  return date >= start ? be : be - 1;
}

function dailyAdYear_(beYear) {
  return Number(beYear) - 543;
}

function dailySongkranStart_(beYear) {
  return new Date(dailyAdYear_(beYear), DAILY_SONGKRAN_START_MONTH, DAILY_SONGKRAN_START_DAY);
}

function dailySongkranEnd_(beYear) {
  return new Date(dailyAdYear_(beYear + 1), DAILY_SONGKRAN_START_MONTH, DAILY_SONGKRAN_START_DAY - 1);
}

function dailyDaysBetween_(a, b) {
  const start = new Date(a.getFullYear(), a.getMonth(), a.getDate());
  const end = new Date(b.getFullYear(), b.getMonth(), b.getDate());
  return Math.round((end - start) / 86400000);
}

function dailyDateKey_(date) {
  if (typeof date === 'string') date = new Date(date);
  return date.getFullYear() + '-' +
    String(date.getMonth() + 1).padStart(2, '0') + '-' +
    String(date.getDate()).padStart(2, '0');
}

function dailyMonthKey_(date) {
  return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0');
}

function dailyZodiacIndexForBEYear_(beYear) {
  return dailyMod_(Number(beYear) - 2563, DAILY_ZODIACS.length);
}

function dailyClashIndex_(index) {
  return dailyMod_(index + 6, DAILY_ZODIACS.length);
}

function dailyStatusFor_(index, annualIndex) {
  if (index === annualIndex) return 'main';
  if (index === dailyClashIndex_(annualIndex)) return 'clash';
  return 'neutral';
}

function dailyClampInt_(value, min, max, fallback) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(max, Math.max(min, Math.trunc(parsed)));
}

return { getDailyData: getDailyData };
})();

const AgeYearService = (() => {
/* 
  ⚠️ [คำเตือนสำคัญที่สุดสำหรับนักพัฒนาและ AI Coding Assistant ในอนาคต]
  แต่ละไฟล์ในระบบดวงชะตานี้มีสิทธิ์เข้าถึงและการจัดวางเลย์เอาต์ (Layout Style) ที่ไม่เหมือนกัน!
  
  🚨 กฎเหล็ก 3 ข้อที่ห้ามละเมิดโดยเด็ดขาด:
  1. 🧮 [ระบบสูตรคำนวณ ห้ามพังเด็ดขาด!]
     ตรรกะการเดินอายุจร การเวียนนักษัตรย้อนทิศทางสำหรับเพศหญิง ตรรกะวันเกิดเริ่มต้นและการสแกน 365 วัน 
     รวมถึงฟังก์ชันคีย์แคช 2 สล็อต (${year}_${gender}) ต้องทำงานได้อย่างถูกต้องแม่นยำ ห้ามดัดแปลงจนสูตรเพี้ยน
  2. 🎨 [จัดรูปแบบโครงสร้าง Layout ให้สวยงามสอดคล้องตามข้อกำหนดเฉพาะของแต่ละไฟล์]
     - ไฟล์ฝั่ง Owner: แสดงผลแท็บควบคุมมุมมอง 4 ปุ่มแบบสมมาตรแนวระนาบเดี่ยวบน Desktop
     - ไฟล์ฝั่ง Teacher และ Public: ซ่อนแท็บ "วันนี้" และ "รายเดือน" และแสดงผลแบบบังคับ 2 ปุ่ม (1fr 1fr)
     - การจัดแนวปุ่ม Stepper และปุ่มลอยรีเซ็ต (↺) ต้องคงความสมดุลกึ่งกลางและลอยตัวสวยงามในทุกสิทธิ์ใช้งาน (ห้ามหล่นบรรทัดล่าง)
  3. 🔌 [ห้ามทำระบบเชื่อมต่อหรือยิง API หา GitHub ส่วนตัวเด็ดขาด!]
     - ห้ามสั่งรันบอตหรือส่งคำขอสแกน (Unauthenticated API requests) ไปยัง api.github.com/repos/... เด็ดขาด
       เพราะระบบรักษาความปลอดภัยของ GitHub จะระงับสิทธิ์ (Suspend) บัญชีผู้ใช้งานทันที!
     - เมื่อทดสอบออฟไลน์โลคอล ให้ทำงานผ่านระบบจำลองออฟไลน์ (Offline Fallback Mock) ในฟังก์ชัน getRunner() เสมอ
     - โฟลเดอร์รูปภาพ chata ต้องใช้ตัวพิมพ์เล็กทั้งหมด (`assets/chata/`) ทั้งหมดในระบบไฟล์และโค้ดเพื่อป้องกันปัญหา 404 บล็อกภาพ
*/

// Server-side calculator for "อายุจรประจำปี" (Public_Age and Teacher_Age).
// Keep annual astrological formulas and house meanings secure on Google's servers.

const AGE_YEAR_MONTHS = [
  { short: 'ม.ค.', full: 'มกราคม' },
  { short: 'ก.พ.', full: 'กุมภาพันธ์' },
  { short: 'มี.ค.', full: 'มีนาคม' },
  { short: 'เม.ย.', full: 'เมษายน' },
  { short: 'พ.ค.', full: 'พฤษภาคม' },
  { short: 'มิ.ย.', full: 'มิถุนายน' },
  { short: 'ก.ค.', full: 'กรกฎาคม' },
  { short: 'ส.ค.', full: 'สิงหาคม' },
  { short: 'ก.ย.', full: 'กันยายน' },
  { short: 'ต.ค.', full: 'ตุลาคม' },
  { short: 'พ.ย.', full: 'พฤศจิกายน' },
  { short: 'ธ.ค.', full: 'ธันวาคม' }
];

const AGE_YEAR_HOUSES = [
  {
    name: 'ตนุ',
    short: 'ตัวเราเอง การเริ่มต้น การตัดสินใจ',
    meaning: 'ตัวเราเองผู้กระทำเอง สั่งการเอง ลงมือเอง ตัดสินใจเอง',
    level: 'neutral'
  },
  {
    name: 'กดุมภะ',
    short: 'การเงิน ทรัพย์ รายรับรายจ่าย',
    meaning: 'การเงิน ข้อนี้มันร้ายนักจะฆ่ากันตายเพราะเรื่องเงิน',
    level: 'neutral'
  },
  {
    name: 'สหัชชะ',
    short: 'การเดินทาง ญาติพี่น้อง เพื่อนฝูง',
    meaning: 'การเดินทางไกล ใกล้ ญาติพี่น้อง เพื่อนฝูง',
    level: 'neutral'
  },
  {
    name: 'พันธุ',
    short: 'บ้าน ที่ดิน พ่อแม่ ญาติ',
    meaning: 'สมบัติ ที่ดิน งานบ้าน งานข้างนอก พ่อ-แม่ ญาติพี่น้อง',
    level: 'neutral'
  },
  {
    name: 'ปุตตะ',
    short: 'รายได้ ลูกบริวาร เงินเข้า',
    meaning: 'รายได้ ลูกบริวาร การใช้จ่าย มีเงินเข้ามา',
    level: 'neutral'
  },
  {
    name: 'อริ',
    short: 'อุปสรรค หนี้สิน ป่วย ถูกโกง',
    meaning: 'อุปสรรค นานา หนี้สิน วิตก ถูกโกง ป่วยไข้ อุบัติเหตุ ถูกจองจำ ตาย',
    level: 'caution'
  },
  {
    name: 'ปัตตนิ',
    short: 'คู่ครอง คู่สัญญา หุ้นส่วน',
    meaning: 'สามี - ภรรยา คู่สัญญา คู่ชู้ หุ้นส่วน คนรู้จักเก่าแก่',
    level: 'neutral'
  },
  {
    name: 'มรณะ',
    short: 'สูญเสีย ห่างไกล ขาดทุน',
    meaning: 'ความตาย สูญเสีย ห่างไกล ว่างเปล่า ขาดทุน เสียหาย ถูกจองจำ ตาย',
    level: 'caution'
  },
  {
    name: 'ศุภะ',
    short: 'ความเจริญรุ่งเรือง',
    meaning: 'ความเจริญรุ่งเรืองส่วนตัว ทั้งในบ้านและที่ทำงาน',
    level: 'good'
  },
  {
    name: 'กัมมะ',
    short: 'งาน การติดต่อ การจัดการ',
    meaning: 'งานที่ติดต่อ บริหารจัดการ ในครัวเรือน และนอกบ้าน',
    level: 'neutral'
  },
  {
    name: 'ลาภะ',
    short: 'โชคลาภ ลาภผล',
    meaning: 'โชคลาภ ลาภผลที่ได้รับมา จะมีจะหมดว่ากันไป',
    level: 'good'
  },
  {
    name: 'วินาศ',
    short: 'สูญเสีย เหนื่อยล้า วิตก',
    meaning: 'ความสูญเสีย เหนื่อยล้า วิตกกังวล ว่างเปล่า ขาดทุน ถูกจองจำ ตาย',
    level: 'caution'
  }
];

const AGE_BIRTH_OPTIONS = {
  showOppositeHouse: true,
  showHouseMeaning: true,
  showAdvice: true
};

function calculateAge(input) {
  const payload = normalizeAgeInput_(input);
  if (payload.error) return payload;

  let result;
  if (payload.mode === 'month') {
    result = buildMonthly_(payload.birthDay, payload.birthMonth, payload.targetMonth, payload.beYear);
  } else if (payload.mode === 'monthYear') {
    result = buildAnnualMonths_(payload.birthDay, payload.birthMonth, payload.beYear);
  } else if (payload.mode === 'yearBirth') {
    result = buildAnnualBirth_(payload.birthDay, payload.birthMonth, payload.birthYear, payload.beYear);
  } else {
    result = buildAnnual_(payload.birthDay, payload.birthMonth, payload.beYear);
  }

  if (result.error) return result;

  return {
    ok: true,
    inputs: payload,
    months: AGE_YEAR_MONTHS,
    summary: result.summary,
    counts: countAgeYearLevels_(result.items),
    items: result.items,
    todayKey: dateKey_(new Date())
  };
}

function calculateAgeToday(input) {
  const base = normalizeAgeInput_(input);
  if (base.error) return base;

  const today = startOfDay_(new Date());
  const periodStart = periodStartForDate_(today, base.birthDay);
  const baseYear = annualBaseYearForDate_(today, base.birthMonth, base.birthDay);
  const annualMode = ['monthYear', 'year', 'yearBirth'].indexOf(base.mode) >= 0;

  const nextInput = {
    birthDay: base.birthDay,
    birthMonth: base.birthMonth,
    birthYear: base.birthYear,
    targetMonth: periodStart.getMonth(),
    beYear: (annualMode ? baseYear : periodStart.getFullYear()) + 543,
    mode: base.mode
  };

  const result = calculateAge(nextInput);
  result.today = {
    targetMonth: nextInput.targetMonth,
    beYear: nextInput.beYear,
    key: dateKey_(today)
  };
  return result;
}

function calculateBirthAge(input) {
  const payload = normalizeBirthAgeInput_(input);
  if (payload.error) return payload;

  const elapsedDays = Math.round((payload.targetDate.getTime() - payload.birthDate.getTime()) / 86400000);
  if (elapsedDays < 0) {
    return {
      ok: false,
      code: 'TARGET_BEFORE_BIRTH',
      message: 'วันที่ดูต้องไม่ก่อนวันเกิด'
    };
  }

  const houseIndex = elapsedDays % AGE_YEAR_HOUSES.length;
  const oppositeIndex = (houseIndex + 6) % AGE_YEAR_HOUSES.length;
  const house = AGE_YEAR_HOUSES[houseIndex];
  const opposite = AGE_YEAR_HOUSES[oppositeIndex];
  const item = {
    key: dateKey_(payload.targetDate),
    date: payload.targetDate.toISOString(),
    order: elapsedDays,
    periodKey: dateKey_(payload.birthDate),
    elapsedDays: elapsedDays,
    birthDateKey: dateKey_(payload.birthDate),
    birthDateLabel: formatAgeYearDate_(payload.birthDate, true, true),
    targetDateLabel: formatAgeYearDate_(payload.targetDate, true, true),
    isBirthAge: true,
    house: ageYearHousePayload_(house, houseIndex),
    opposite: ageYearHousePayload_(opposite, oppositeIndex)
  };

  return {
    ok: true,
    mode: 'birth',
    inputs: payload.normalized,
    months: AGE_YEAR_MONTHS,
    summary: item.birthDateLabel + ' ถึง ' + item.targetDateLabel + ' · นับได้ ' + elapsedDays + ' วัน',
    counts: countAgeYearLevels_([item]),
    items: [item],
    item: item,
    pairLabel: house.name + ' -> ' + opposite.name,
    displayOptions: AGE_BIRTH_OPTIONS,
    todayKey: dateKey_(new Date())
  };
}

function calculateBirthAgeToday(input) {
  const today = startOfDay_(new Date());
  const source = input || {};
  const nextInput = {
    birthDay: source.birthDay,
    birthMonth: source.birthMonth,
    birthYear: source.birthYear,
    targetDay: today.getDate(),
    targetMonth: today.getMonth(),
    targetYear: today.getFullYear() + 543
  };
  const result = calculateBirthAge(nextInput);
  if (result && result.ok) {
    result.today = {
      targetDay: nextInput.targetDay,
      targetMonth: nextInput.targetMonth,
      targetYear: nextInput.targetYear,
      key: dateKey_(today)
    };
  }
  return result;
}

function normalizeAgeInput_(input) {
  const source = input || {};
  const birthDay = clampInt_(source.birthDay, 1, 31, 29);
  const birthMonth = clampInt_(source.birthMonth, 0, 11, 0);
  const targetMonth = clampInt_(source.targetMonth, 0, 11, birthMonth);
  const beYear = clampInt_(source.beYear, 1, 3000, new Date().getFullYear() + 543);
  const birthYear = clampInt_(source.birthYear, 1, 3000, 2488);
  const mode = ['month', 'monthYear', 'year', 'yearBirth'].indexOf(source.mode) >= 0 ? source.mode : 'month';

  return {
    birthDay: birthDay,
    birthMonth: birthMonth,
    birthYear: birthYear,
    targetMonth: targetMonth,
    beYear: beYear,
    adYear: beYear - 543,
    mode: mode
  };
}

function normalizeBirthAgeInput_(input) {
  const source = input || {};
  const now = startOfDay_(new Date());
  const birthYear = clampInt_(source.birthYear, 1, 3000, 2488);
  const birthMonth = clampInt_(source.birthMonth, 0, 11, 6);
  const targetYear = clampInt_(source.targetYear, 1, 3000, now.getFullYear() + 543);
  const targetMonth = clampInt_(source.targetMonth, 0, 11, now.getMonth());
  const birthDay = clampInt_(source.birthDay, 1, 31, 29);
  const targetDay = clampInt_(source.targetDay, 1, 31, now.getDate());
  const birthDate = buildBirthAgeDate_(birthYear, birthMonth, birthDay);
  const targetDate = buildBirthAgeDate_(targetYear, targetMonth, targetDay);

  return {
    birthDate: birthDate,
    targetDate: targetDate,
    normalized: {
      birthDay: birthDate.getDate(),
      birthMonth: birthDate.getMonth(),
      birthYear: birthDate.getFullYear() + 543,
      targetDay: targetDate.getDate(),
      targetMonth: targetDate.getMonth(),
      targetYear: targetDate.getFullYear() + 543
    }
  };
}

function buildBirthAgeDate_(beYear, monthIndex, day) {
  const adYear = beYear - 543;
  const safeDay = Math.min(day, daysInAgeYearMonth_(adYear, monthIndex));
  return startOfDay_(new Date(adYear, monthIndex, safeDay));
}

function buildMonthly_(birthDay, birthMonth, targetMonth, beYear) {
  const adYear = beYear - 543;
  const startYear = adYear;
  const start = cycleStartForMonth_(startYear, targetMonth, birthDay);
  const nextMonth = targetMonth === 11 ? 0 : targetMonth + 1;
  const nextYear = targetMonth === 11 ? startYear + 1 : startYear;
  const end = cycleStartForMonth_(nextYear, nextMonth, birthDay);
  
  const items = [];
  let index = 0;
  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const houseIndex = index % AGE_YEAR_HOUSES.length;
    const house = AGE_YEAR_HOUSES[houseIndex];
    const d = new Date(cursor);
    items.push({
      key: dateKey_(d),
      date: d.toISOString(),
      order: index,
      periodKey: dateKey_(d),
      house: ageYearHousePayload_(house, houseIndex)
    });
    index++;
  }

  const endDisplay = new Date(end.getTime() - 86400000);
  return {
    items: items,
    summary: formatAgeYearDate_(start, true) + ' ถึง ' + formatAgeYearDate_(endDisplay, true)
  };
}

function buildAnnual_(birthDay, birthMonth, beYear) {
  const adYear = beYear - 543;
  const start = cycleStartForMonth_(adYear, birthMonth, birthDay);
  const end = cycleStartForMonth_(adYear + 1, birthMonth, birthDay);
  const items = [];

  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const itemDate = new Date(cursor);
    const periodStart = periodStartForDate_(itemDate, birthDay);
    const offset = Math.round((itemDate.getTime() - periodStart.getTime()) / 86400000);
    const houseIndex = offset % AGE_YEAR_HOUSES.length;
    const house = AGE_YEAR_HOUSES[houseIndex];
    items.push({
      key: dateKey_(cursor),
      date: itemDate.toISOString(),
      order: offset,
      periodKey: dateKey_(periodStart),
      house: ageYearHousePayload_(house, houseIndex)
    });
  }

  const endDisplay = new Date(end.getTime() - 86400000);
  return {
    items: items,
    summary: formatAgeYearDate_(start, true) + ' ถึง ' + formatAgeYearDate_(endDisplay, true)
  };
}

function buildAnnualMonths_(birthDay, birthMonth, beYear) {
  const annual = buildAnnual_(birthDay, birthMonth, beYear);
  if (annual.error) return annual;

  const starts = annual.items.filter(function(item) {
    return item.order === 0;
  }).slice(0, 12);

  const items = starts.map(function(startItem, index) {
    const nextStart = starts[index + 1];
    const endKey = nextStart ? previousDateKey_(nextStart.key) : annual.items[annual.items.length - 1].key;
    const houseIndex = index % AGE_YEAR_HOUSES.length;
    const house = AGE_YEAR_HOUSES[houseIndex];
    return {
      key: startItem.key,
      date: startItem.key,
      endDate: endKey,
      order: index,
      periodKey: startItem.periodKey || startItem.key,
      isPeriod: true,
      house: ageYearHousePayload_(house, houseIndex)
    };
  });

  return {
    items: items,
    summary: formatAgeYearDate_(starts[0].key, true) + ' ถึง ' + formatAgeYearDate_(items[items.length - 1].endDate, true)
  };
}

function buildAnnualBirth_(birthDay, birthMonth, birthYear, beYear) {
  const adYear = beYear - 543;
  const start = cycleStartForMonth_(adYear, birthMonth, birthDay);
  const end = cycleStartForMonth_(adYear + 1, birthMonth, birthDay);
  const birthAnchor = buildBirthAgeDate_(birthYear, birthMonth, birthDay);
  if (start.getTime() < birthAnchor.getTime()) {
    return {
      ok: false,
      error: true,
      code: 'YEAR_BEFORE_BIRTH',
      message: 'ปีที่ดูต้องไม่ก่อนปีเกิดจริง'
    };
  }
  const items = [];

  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const itemDate = new Date(cursor);
    const periodStart = periodStartForDate_(itemDate, birthDay);
    const offset = Math.round((itemDate.getTime() - periodStart.getTime()) / 86400000);
    const elapsedDays = Math.round((itemDate.getTime() - birthAnchor.getTime()) / 86400000);
    const houseIndex = elapsedDays % AGE_YEAR_HOUSES.length;
    const house = AGE_YEAR_HOUSES[houseIndex];
    items.push({
      key: dateKey_(cursor),
      date: itemDate.toISOString(),
      order: offset,
      periodKey: dateKey_(periodStart),
      elapsedDays: elapsedDays,
      birthDateKey: dateKey_(birthAnchor),
      house: ageYearHousePayload_(house, houseIndex)
    });
  }

  const endDisplay = new Date(end.getTime() - 86400000);
  return {
    items: items,
    summary: formatAgeYearDate_(start, true) + ' ถึง ' + formatAgeYearDate_(endDisplay, true)
  };
}


function countAgeYearLevels_(items) {
  return items.reduce(function(acc, item) {
    const level = item.house.level;
    acc.all++;
    acc[level] = (acc[level] || 0) + 1;
    return acc;
  }, { all: 0, good: 0, neutral: 0, caution: 0 });
}

function ageYearHousePayload_(house, houseIndex) {
  const opposite = AGE_YEAR_HOUSES[(houseIndex + 6) % AGE_YEAR_HOUSES.length];
  return {
    name: house.name,
    short: house.short,
    meaning: house.meaning,
    level: house.level,
    oppositeName: opposite.name
  };
}

function cycleStartForMonth_(adYear, monthIndex, day) {
  return new Date(adYear, monthIndex, Math.min(day, daysInAgeYearMonth_(adYear, monthIndex)));
}

function previousMonthParts_(adYear, monthIndex) {
  return monthIndex === 0
    ? { year: adYear - 1, month: 11 }
    : { year: adYear, month: monthIndex - 1 };
}

function cycleStartForOffset_(adYear, birthMonth, birthDay, offset) {
  const absoluteMonth = birthMonth + offset;
  const year = adYear + Math.floor(absoluteMonth / 12);
  const month = ((absoluteMonth % 12) + 12) % 12;
  return cycleStartForMonth_(year, month, birthDay);
}

function annualPeriodStarts_(adYear, birthMonth, birthDay) {
  const starts = [];
  for (let index = 0; index < 13; index++) {
    starts.push(cycleStartForOffset_(adYear, birthMonth, birthDay, index));
  }
  return starts;
}

function cycleYearForMonth_(adYear, birthMonth, targetMonth) {
  return targetMonth < birthMonth ? adYear + 1 : adYear;
}

function annualBaseYearForDate_(date, birthMonth, birthDay) {
  const startThisYear = cycleStartForMonth_(date.getFullYear(), birthMonth, birthDay);
  return date < startThisYear ? date.getFullYear() - 1 : date.getFullYear();
}

function periodStartForDate_(date, birthDay) {
  let start = cycleStartForMonth_(date.getFullYear(), date.getMonth(), birthDay);
  if (date < start) {
    const previous = previousMonthParts_(date.getFullYear(), date.getMonth());
    start = cycleStartForMonth_(previous.year, previous.month, birthDay);
  }
  return start;
}

function daysInAgeYearMonth_(adYear, monthIndex) {
  return new Date(adYear, monthIndex + 1, 0).getDate();
}

function startOfDay_(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function dateKey_(date) {
  if (typeof date === 'string') date = new Date(date);
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return y + '-' + m + '-' + d;
}

function dateFromKey_(key) {
  const parts = String(key || '').split('-').map(function(part) {
    return Number(part);
  });
  if (parts.length !== 3 || parts.some(function(part) { return !Number.isFinite(part); })) {
    return startOfDay_(new Date());
  }
  return new Date(parts[0], parts[1] - 1, parts[2]);
}

function previousDateKey_(key) {
  const date = dateFromKey_(key);
  date.setDate(date.getDate() - 1);
  return dateKey_(date);
}

function formatAgeYearDate_(date, includeYear, includeDayName) {
  if (typeof date === 'string') date = dateFromKey_(date);
  const base = date.getDate() + ' ' + AGE_YEAR_MONTHS[date.getMonth()].short;
  const formatted = includeYear ? base + ' ' + (date.getFullYear() + 543) : base;
  if (includeDayName) {
    const DAY_NAMES = ['วันอาทิตย์', 'วันจันทร์', 'วันอังคาร', 'วันพุธ', 'วันพฤหัสบดี', 'วันศุกร์', 'วันเสาร์'];
    return DAY_NAMES[date.getDay()] + ' ' + formatted;
  }
  return formatted;
}

function clampInt_(value, min, max, fallback) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.min(max, Math.max(min, Math.trunc(number)));
}

return { calculateAge: calculateAge, calculateAgeToday: calculateAgeToday, calculateBirthAge: calculateBirthAge, calculateBirthAgeToday: calculateBirthAgeToday };
})();

const AgeMonthService = (() => {
/* 
  ⚠️ [คำเตือนสำคัญที่สุดสำหรับนักพัฒนาและ AI Coding Assistant ในอนาคต]
  แต่ละไฟล์ในระบบดวงชะตานี้มีสิทธิ์เข้าถึงและการจัดวางเลย์เอาต์ (Layout Style) ที่ไม่เหมือนกัน!
  
  🚨 กฎเหล็ก 3 ข้อที่ห้ามละเมิดโดยเด็ดขาด:
  1. 🧮 [ระบบสูตรคำนวณ ห้ามพังเด็ดขาด!]
     ตรรกะการเดินอายุจร การเวียนนักษัตรย้อนทิศทางสำหรับเพศหญิง ตรรกะวันเกิดเริ่มต้นและการสแกน 365 วัน 
     รวมถึงฟังก์ชันคีย์แคช 2 สล็อต (${year}_${gender}) ต้องทำงานได้อย่างถูกต้องแม่นยำ ห้ามดัดแปลงจนสูตรเพี้ยน
  2. 🎨 [จัดรูปแบบโครงสร้าง Layout ให้สวยงามสอดคล้องตามข้อกำหนดเฉพาะของแต่ละไฟล์]
     - ไฟล์ฝั่ง Owner: แสดงผลแท็บควบคุมมุมมอง 4 ปุ่มแบบสมมาตรแนวระนาบเดี่ยวบน Desktop
     - ไฟล์ฝั่ง Teacher และ Public: ซ่อนแท็บ "วันนี้" และ "รายเดือน" และแสดงผลแบบบังคับ 2 ปุ่ม (1fr 1fr)
     - การจัดแนวปุ่ม Stepper และปุ่มลอยรีเซ็ต (↺) ต้องคงความสมดุลกึ่งกลางและลอยตัวสวยงามในทุกสิทธิ์ใช้งาน (ห้ามหล่นบรรทัดล่าง)
  3. 🔌 [ห้ามทำระบบเชื่อมต่อหรือยิง API หา GitHub ส่วนตัวเด็ดขาด!]
     - ห้ามสั่งรันบอตหรือส่งคำขอสแกน (Unauthenticated API requests) ไปยัง api.github.com/repos/... เด็ดขาด
       เพราะระบบรักษาความปลอดภัยของ GitHub จะระงับสิทธิ์ (Suspend) บัญชีผู้ใช้งานทันที!
     - เมื่อทดสอบออฟไลน์โลคอล ให้ทำงานผ่านระบบจำลองออฟไลน์ (Offline Fallback Mock) ในฟังก์ชัน getRunner() เสมอ
     - โฟลเดอร์รูปภาพ chata ต้องใช้ตัวพิมพ์เล็กทั้งหมด (`assets/chata/`) ทั้งหมดในระบบไฟล์และโค้ดเพื่อป้องกันปัญหา 404 บล็อกภาพ
*/

// Server-side calculator for the public "อายุจรประจำเดือน" page.
// Keep formulas and house meanings here so they are not sent as browser JavaScript.

const AGE_MONTHS = [
  { short: 'ม.ค.', full: 'มกราคม' },
  { short: 'ก.พ.', full: 'กุมภาพันธ์' },
  { short: 'มี.ค.', full: 'มีนาคม' },
  { short: 'เม.ย.', full: 'เมษายน' },
  { short: 'พ.ค.', full: 'พฤษภาคม' },
  { short: 'มิ.ย.', full: 'มิถุนายน' },
  { short: 'ก.ค.', full: 'กรกฎาคม' },
  { short: 'ส.ค.', full: 'สิงหาคม' },
  { short: 'ก.ย.', full: 'กันยายน' },
  { short: 'ต.ค.', full: 'ตุลาคม' },
  { short: 'พ.ย.', full: 'พฤศจิกายน' },
  { short: 'ธ.ค.', full: 'ธันวาคม' }
];

const AGE_HOUSES = [
  {
    name: 'ตนุ',
    short: 'ตัวเอง การเริ่มต้น การตัดสินใจ',
    meaning: 'เรือนตัวเองโดยตรง เหมาะกับการตั้งหลัก ดูแลสุขภาพ วางแผนชีวิต ตัดสินใจเรื่องสำคัญ และเริ่มสิ่งที่ต้องใช้ตัวคุณเป็นหลัก',
    level: 'neutral'
  },
  {
    name: 'กดุมภะ',
    short: 'การเงิน ทรัพย์ รายรับรายจ่าย',
    meaning: 'เรือนเงินทอง รายได้ ทรัพย์สิน และของมีค่า เหมาะกับการจัดบัญชี เคลียร์หนี้ วางแผนรายรับรายจ่าย แต่ไม่ควรประมาทเรื่องเงิน',
    level: 'neutral'
  },
  {
    name: 'สหัชชะ',
    short: 'การเดินทาง ญาติพี่น้อง เพื่อนฝูง',
    meaning: 'เรือนการติดต่อ เดินทางใกล้ การสื่อสาร พี่น้อง ญาติ และเพื่อน เหมาะกับการเจรจา นัดหมาย ประสานงาน และทำเรื่องที่ต้องพูดคุย',
    level: 'neutral'
  },
  {
    name: 'พันธุ',
    short: 'บ้าน ที่ดิน พ่อแม่ ญาติ',
    meaning: 'เรือนบ้าน ครอบครัว ที่อยู่อาศัย ที่ดิน พ่อแม่ และญาติ เหมาะกับการดูแลบ้าน จัดการเรื่องครอบครัว หรือวางแผนทรัพย์สินในครัวเรือน',
    level: 'neutral'
  },
  {
    name: 'ปุตตะ',
    short: 'รายได้ ลูกบริวาร เงินเข้า',
    meaning: 'เรือนลูกหลาน บริวาร ความสุข ความคิดสร้างสรรค์ และรายได้ที่พอมีเข้ามา เหมาะกับงานที่ต้องใช้ไอเดีย คนช่วย หรือแรงสนับสนุน',
    level: 'neutral'
  },
  {
    name: 'อริ',
    short: 'อุปสรรค หนี้สิน ป่วย ถูกโกง',
    meaning: 'เรือนอุปสรรค โรคภัย หนี้สิน คนขัดขวาง และเรื่องที่ทำให้เหนื่อย ควรระวังการปะทะ การเซ็นรับภาระ หนี้สิน การถูกโกง และอุบัติเหตุ',
    level: 'caution'
  },
  {
    name: 'ปัตตนิ',
    short: 'คู่ครอง คู่สัญญา หุ้นส่วน',
    meaning: 'เรือนคู่ครอง คู่สัญญา หุ้นส่วน และคนที่ต้องตกลงกัน เหมาะกับการพูดให้ชัด ทำข้อตกลงให้รอบคอบ และระวังความเข้าใจผิดในความสัมพันธ์',
    level: 'neutral'
  },
  {
    name: 'มรณะ',
    short: 'สูญเสีย ห่างไกล ขาดทุน',
    meaning: 'เรือนการเปลี่ยนแปลง การสูญเสีย ของหาย เสียเงิน หรือเรื่องที่ต้องตัดใจ ควรหลีกเลี่ยงการเริ่มเรื่องเสี่ยง ระวังสุขภาพและทรัพย์สิน',
    level: 'caution'
  },
  {
    name: 'ศุภะ',
    short: 'ความเจริญรุ่งเรือง',
    meaning: 'เรือนความเจริญ ผู้ใหญ่ ครู อาจารย์ บุญกุศล และการเดินทางไกล เหมาะกับการขอความช่วยเหลือ ติดต่อผู้ใหญ่ เรียนรู้ หรือทำบุญ',
    level: 'good'
  },
  {
    name: 'กัมมะ',
    short: 'งาน การติดต่อ การจัดการ',
    meaning: 'เรือนงาน หน้าที่ ความรับผิดชอบ และชื่อเสียง เหมาะกับการจัดการงาน ติดตามงาน วางระบบ และแสดงความสามารถให้คนเห็น',
    level: 'neutral'
  },
  {
    name: 'ลาภะ',
    short: 'โชคลาภ ลาภผล',
    meaning: 'เรือนลาภ โอกาส เพื่อน ผู้สนับสนุน และผลตอบแทน เหมาะกับการรับโอกาส ติดต่อเครือข่าย และเก็บเกี่ยวผลจากสิ่งที่ทำไว้',
    level: 'good'
  },
  {
    name: 'วินาศ',
    short: 'สูญเสีย เหนื่อยล้า วิตก',
    meaning: 'เรือนเรื่องซ่อนเร้น ความลับ ความเหนื่อย ความสูญเสีย และสิ่งที่ควบคุมยาก ควรทำตัวเงียบ รอบคอบ พักผ่อน และเลี่ยงการเสี่ยง',
    level: 'caution'
  }
];

function calculateAgeMonth(input) {
  const payload = normalizeAgeMonthInput_(input);
  if (payload.error) return payload;

  const result = buildAgeMonth_(payload.birthDay, payload.birthMonth, payload.targetMonth, payload.beYear);
  return {
    ok: true,
    inputs: payload,
    months: AGE_MONTHS,
    summary: result.summary,
    counts: countAgeLevels_(result.items),
    items: result.items,
    todayKey: dateKey_(new Date())
  };
}

function calculateAgeMonthToday(input) {
  const base = normalizeAgeMonthInput_(input);
  if (base.error) return base;

  const today = startOfDay_(new Date());
  const periodStart = periodStartForDate_(today, base.birthDay);
  const baseYear = annualBaseYearForDate_(today, base.birthMonth, base.birthDay);
  const nextInput = {
    birthDay: base.birthDay,
    birthMonth: base.birthMonth,
    targetMonth: periodStart.getMonth(),
    beYear: periodStart.getFullYear() + 543
  };
  const result = calculateAgeMonth(nextInput);
  result.today = {
    targetMonth: nextInput.targetMonth,
    beYear: nextInput.beYear,
    key: dateKey_(today)
  };
  return result;
}

function normalizeAgeMonthInput_(input) {
  const source = input || {};
  const birthDay = clampInt_(source.birthDay, 1, 31, 29);
  const birthMonth = clampInt_(source.birthMonth, 0, 11, 0);
  const targetMonth = clampInt_(source.targetMonth, 0, 11, birthMonth);
  const beYear = clampInt_(source.beYear, 1, 3000, new Date().getFullYear() + 543);

  return {
    birthDay: birthDay,
    birthMonth: birthMonth,
    targetMonth: targetMonth,
    beYear: beYear,
    adYear: beYear - 543
  };
}

function buildAgeMonth_(birthDay, birthMonth, targetMonth, beYear) {
  const adYear = beYear - 543;
  const startYear = adYear;
  const start = cycleStartForMonth_(startYear, targetMonth, birthDay);
  const nextMonth = targetMonth === 11 ? 0 : targetMonth + 1;
  const nextYear = targetMonth === 11 ? startYear + 1 : startYear;
  const end = cycleStartForMonth_(nextYear, nextMonth, birthDay);
  const items = [];
  let order = 0;

  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const date = new Date(cursor);
    const house = AGE_HOUSES[order % AGE_HOUSES.length];
    items.push({
      key: dateKey_(date),
      dateLabel: formatAgeDate_(date, false),
      fullDateLabel: formatAgeDate_(date, true),
      house: {
        name: house.name,
        short: house.short,
        meaning: house.meaning,
        level: house.level
      },
      order: order
    });
    order++;
  }

  const endDisplay = new Date(end.getFullYear(), end.getMonth(), end.getDate() - 1);
  return {
    items: items,
    summary: formatAgeDate_(start, true) + ' ถึง ' + formatAgeDate_(endDisplay, true)
  };
}

function countAgeLevels_(items) {
  return items.reduce(function(acc, item) {
    const level = item.house.level;
    acc.all++;
    acc[level] = (acc[level] || 0) + 1;
    return acc;
  }, { all: 0, good: 0, neutral: 0, caution: 0 });
}

function cycleYearForMonth_(adYear, birthMonth, targetMonth) {
  return targetMonth < birthMonth ? adYear + 1 : adYear;
}

function cycleStartForMonth_(adYear, monthIndex, day) {
  return new Date(adYear, monthIndex, Math.min(day, daysInAgeMonth_(adYear, monthIndex)));
}

function previousMonthParts_(adYear, monthIndex) {
  return monthIndex === 0
    ? { year: adYear - 1, month: 11 }
    : { year: adYear, month: monthIndex - 1 };
}

function periodStartForDate_(date, birthDay) {
  let start = cycleStartForMonth_(date.getFullYear(), date.getMonth(), birthDay);
  if (date < start) {
    const previous = previousMonthParts_(date.getFullYear(), date.getMonth());
    start = cycleStartForMonth_(previous.year, previous.month, birthDay);
  }
  return start;
}

function annualBaseYearForDate_(date, birthMonth, birthDay) {
  const startThisYear = cycleStartForMonth_(date.getFullYear(), birthMonth, birthDay);
  return date < startThisYear ? date.getFullYear() - 1 : date.getFullYear();
}

function daysInAgeMonth_(adYear, monthIndex) {
  return new Date(adYear, monthIndex + 1, 0).getDate();
}

function startOfDay_(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function dateKey_(date) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return y + '-' + m + '-' + d;
}

function formatAgeDate_(date, includeYear) {
  const base = date.getDate() + ' ' + AGE_MONTHS[date.getMonth()].short;
  return includeYear ? base + ' ' + (date.getFullYear() + 543) : base;
}

function clampInt_(value, min, max, fallback) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.min(max, Math.max(min, Math.trunc(number)));
}

return { calculateAgeMonth: calculateAgeMonth, calculateAgeMonthToday: calculateAgeMonthToday };
})();

const OwnerAgeService = (() => {
/* 
  ⚠️ [คำเตือนสำคัญที่สุดสำหรับนักพัฒนาและ AI Coding Assistant ในอนาคต]
  แต่ละไฟล์ในระบบดวงชะตานี้มีสิทธิ์เข้าถึงและการจัดวางเลย์เอาต์ (Layout Style) ที่ไม่เหมือนกัน!
  
  🚨 กฎเหล็ก 3 ข้อที่ห้ามละเมิดโดยเด็ดขาด:
  1. 🧮 [ระบบสูตรคำนวณ ห้ามพังเด็ดขาด!]
     ตรรกะการเดินอายุจร การเวียนนักษัตรย้อนทิศทางสำหรับเพศหญิง ตรรกะวันเกิดเริ่มต้นและการสแกน 365 วัน 
     รวมถึงฟังก์ชันคีย์แคช 2 สล็อต (${year}_${gender}) ต้องทำงานได้อย่างถูกต้องแม่นยำ ห้ามดัดแปลงจนสูตรเพี้ยน
  2. 🎨 [จัดรูปแบบโครงสร้าง Layout ให้สวยงามสอดคล้องตามข้อกำหนดเฉพาะของแต่ละไฟล์]
     - ไฟล์ฝั่ง Owner: แสดงผลแท็บควบคุมมุมมอง 4 ปุ่มแบบสมมาตรแนวระนาบเดี่ยวบน Desktop
     - ไฟล์ฝั่ง Teacher และ Public: ซ่อนแท็บ "วันนี้" และ "รายเดือน" และแสดงผลแบบบังคับ 2 ปุ่ม (1fr 1fr)
     - การจัดแนวปุ่ม Stepper และปุ่มลอยรีเซ็ต (↺) ต้องคงความสมดุลกึ่งกลางและลอยตัวสวยงามในทุกสิทธิ์ใช้งาน (ห้ามหล่นบรรทัดล่าง)
  3. 🔌 [ห้ามทำระบบเชื่อมต่อหรือยิง API หา GitHub ส่วนตัวเด็ดขาด!]
     - ห้ามสั่งรันบอตหรือส่งคำขอสแกน (Unauthenticated API requests) ไปยัง api.github.com/repos/... เด็ดขาด
       เพราะระบบรักษาความปลอดภัยของ GitHub จะระงับสิทธิ์ (Suspend) บัญชีผู้ใช้งานทันที!
     - เมื่อทดสอบออฟไลน์โลคอล ให้ทำงานผ่านระบบจำลองออฟไลน์ (Offline Fallback Mock) ในฟังก์ชัน getRunner() เสมอ
     - โฟลเดอร์รูปภาพ chata ต้องใช้ตัวพิมพ์เล็กทั้งหมด (`assets/chata/`) ทั้งหมดในระบบไฟล์และโค้ดเพื่อป้องกันปัญหา 404 บล็อกภาพ
*/

// Owner-only server-side calculator for age-cycle.
// Keeps the private long-form predictions separate from Public_Age and Teacher_Age.

const OWNER_AGE_MONTHS = [
  { short: 'ม.ค.', full: 'มกราคม' },
  { short: 'ก.พ.', full: 'กุมภาพันธ์' },
  { short: 'มี.ค.', full: 'มีนาคม' },
  { short: 'เม.ย.', full: 'เมษายน' },
  { short: 'พ.ค.', full: 'พฤษภาคม' },
  { short: 'มิ.ย.', full: 'มิถุนายน' },
  { short: 'ก.ค.', full: 'กรกฎาคม' },
  { short: 'ส.ค.', full: 'สิงหาคม' },
  { short: 'ก.ย.', full: 'กันยายน' },
  { short: 'ต.ค.', full: 'ตุลาคม' },
  { short: 'พ.ย.', full: 'พฤศจิกายน' },
  { short: 'ธ.ค.', full: 'ธันวาคม' }
];

const OWNER_AGE_HOUSES = [
      {
        name: 'ตนุ',
        short: 'ตัวเราเอง การเริ่มต้น การตัดสินใจ',
        meaning: 'ตัวเราเองผู้กระทำเอง สั่งการเอง ลงมือเอง ตัดสินใจเอง',
        oracle: 'ดวงวันนี้กลับมาอยู่ที่ตัวคุณเองโดยตรง',
        plain: 'ตนุคือวันที่ตัวคุณเป็นต้นเหตุของเรื่องทั้งหมด คิดอย่างไร ตัดสินใจอย่างไร พูดอย่างไร จะส่งแรงกลับมาหาตัวเองเร็วเป็นพิเศษ วันนี้ไม่ใช่วันรอคนอื่นนำ แต่เป็นวันตั้งหลักจากใจตัวเอง',
        do: [
          'ตั้งเป้าใหม่ เริ่มเรื่องที่ต้องใช้ความกล้า หรือเคลียร์สิ่งที่ค้างในใจ',
          'ดูแลร่างกาย หน้าตา บุคลิก และความพร้อมก่อนออกไปเจอคน',
          'ถ้ามีเรื่องต้องเลือก ให้ถามตัวเองตรงๆ ว่าทางไหนทำแล้วไม่เสียศักดิ์ศรีตัวเอง'
        ],
        watch: [
          'อารมณ์ขึ้นง่าย เพราะวันนี้เอาเรื่องเข้าตัวง่ายกว่าปกติ',
          'อย่าตัดสินใจเร็วเพียงเพราะอยากให้ทุกอย่างจบไว'
        ],
        example: 'ถ้าจะสมัครงาน เปลี่ยนลุค เริ่มออกกำลัง หรือเปิดบทสนทนาสำคัญ วันนี้พอใช้ได้ เพราะพลังดวงอยู่ที่ตัวคุณ แต่ต้องเดินด้วยสติ ไม่ใช่เดินด้วยความหุนหัน',
        level: 'neutral'
      },
      {
        name: 'กดุมภะ',
        short: 'การเงิน ทรัพย์ รายรับรายจ่าย',
        meaning: 'การเงิน ข้อนี้มันร้ายนักจะฆ่ากันตายเพราะเรื่องเงิน',
        oracle: 'เรื่องเงินพูดเบาๆ วันนี้ก็กลายเป็นเรื่องใหญ่ได้',
        plain: 'กดุมภะไม่ได้แปลว่าเงินเข้าอย่างเดียว แต่แปลว่าเงินกำลังมีน้ำหนัก รายรับ รายจ่าย ทรัพย์สิน ราคา หนี้ และคำสัญญาเรื่องผลประโยชน์จะเด่นขึ้นมา ใครคุยไม่ชัดวันนี้มีสิทธิ์ผิดใจกัน',
        do: [
          'นับเงิน เช็กยอด โอน รับ จ่าย ให้ถูกทุกตัวเลข',
          'คุยราคา ค่าจ้าง ค่าของ หรือส่วนแบ่งให้ชัดก่อนตกลง',
          'เรื่องยืมเงิน ทวงเงิน หรือแบ่งผลประโยชน์ ควรมีหลักฐาน'
        ],
        watch: [
          'ระวังใจอ่อนกับคำขอเรื่องเงิน เพราะปลายทางอาจกลายเป็นภาระ',
          'อย่าซื้อของเพื่อแก้อารมณ์ เสียดายทีหลังได้ง่าย'
        ],
        example: 'ภาพของวันนี้คือ ลูกค้าต่อราคา คนมายืมเงิน ค่าใช้จ่ายแทรก หรือของที่คิดว่าถูกกลับมีเงื่อนไขเพิ่ม อ่านตัวเลขให้จบก่อนพยักหน้า',
        level: 'neutral'
      },
      {
        name: 'สหัชชะ',
        short: 'การเดินทาง ญาติพี่น้อง เพื่อนฝูง',
        meaning: 'การเดินทางไกล ใกล้ ญาติพี่น้อง เพื่อนฝูง',
        oracle: 'ข่าว คนใกล้ตัว และการเดินทางสั้นๆ จะขยับดวงวันนี้',
        plain: 'สหัชชะคือเรือนของเสียง ข้อความ ทางผ่าน และคนใกล้ตัว วันนี้เรื่องไม่ได้มาแบบใหญ่โต แต่มาเป็นสาย โทรศัพท์ แชต นัดหมาย เอกสาร หรือธุระเล็กหลายชิ้นที่ต่อกันจนเต็มวัน',
        do: [
          'โทร นัด ส่งเอกสาร ประสานงาน หรือเคลียร์ข้อความที่ค้างไว้',
          'ใช้เครือข่ายใกล้ตัว เพื่อน พี่น้อง ญาติ ให้ช่วยเปิดทาง',
          'จัดลำดับธุระให้ดี เพราะอาจมีหลายจุดให้วิ่งในวันเดียว'
        ],
        watch: [
          'ข้อความสั้นๆ อาจทำให้เข้าใจผิด ควรอ่านก่อนส่ง',
          'การเดินทางใกล้ๆ อย่าชะล่าใจ เผื่อเวลาสำหรับเรื่องแทรก'
        ],
        example: 'วันนี้อาจไม่เหนื่อยจากงานใหญ่ แต่เหนื่อยจากการตอบคน วิ่งส่งของ แวะรับเอกสาร หรือแก้ความเข้าใจผิดเล็กๆ ที่ถ้าปล่อยไว้จะยาว',
        level: 'neutral'
      },
      {
        name: 'พันธุ',
        short: 'บ้าน ที่ดิน พ่อแม่ ญาติ',
        meaning: 'สมบัติ ที่ดิน งานบ้าน งานข้างนอก พ่อ-แม่ ญาติพี่น้อง',
        oracle: 'ฐานชีวิต บ้าน ครอบครัว และของมั่นคงเรียกให้หันกลับไปดู',
        plain: 'พันธุคือรากของชีวิต บ้าน รถ ที่ดิน ญาติ ผู้ใหญ่ และเรื่องที่ทำให้รู้สึกมั่นคง วันนี้ดวงจะพาคุณกลับไปแตะเรื่องในบ้าน หรือเรื่องเก่าที่เป็นฐานรองรับชีวิต',
        do: [
          'จัดบ้าน ซ่อมของ ดูรถ ดูเอกสารบ้าน ที่ดิน หรือทรัพย์สิน',
          'คุยกับพ่อแม่ ญาติ หรือผู้ใหญ่ในบ้านด้วยน้ำเสียงที่นิ่ง',
          'ตัดสินใจเรื่องที่อยู่อาศัย ของใช้จำเป็น หรือความมั่นคงระยะยาว'
        ],
        watch: [
          'เรื่องเก่าในครอบครัวถูกสะกิดแล้วอารมณ์ขึ้นง่าย',
          'ของใหญ่ เอกสารใหญ่ ต้องดูให้ครบ อย่าเชื่อแค่คำพูด'
        ],
        example: 'ถ้าไฟเสีย รถมีเสียง ญาติโทรมา หรือผู้ใหญ่ในบ้านมีเรื่องให้ช่วย นั่นแหละคือพันธุทำงาน วันนี้ดูแลฐานให้แน่นก่อนค่อยไปลุยเรื่องนอกบ้าน',
        level: 'neutral'
      },
      {
        name: 'ปุตตะ',
        short: 'รายได้ ลูกบริวาร เงินเข้า',
        meaning: 'รายได้ ลูกบริวาร การใช้จ่าย มีเงินเข้ามา',
        oracle: 'ความสุข ไอเดีย และคนที่อยู่ใต้การดูแลจะส่งสัญญาณ',
        plain: 'ปุตตะคือสิ่งที่เราสร้างแล้วอยากเห็นมันโต อาจเป็นลูก หลาน ลูกน้อง งานสร้างสรรค์ คอนเทนต์ งานเสริม หรือความสุขเล็กๆ วันนี้ใจจะอยากทำอะไรที่มีชีวิตชีวามากกว่าทำตามหน้าที่เฉยๆ',
        do: [
          'เขียน คิด ทำคอนเทนต์ ทดลองไอเดีย หรือเริ่มงานที่ต้องใช้เสน่ห์',
          'ให้เวลากับลูกหลาน บริวาร หรือลูกน้องที่ต้องการคำแนะนำ',
          'รับงานเล็ก รายได้เสริม หรือโอกาสที่มาจากความถนัดส่วนตัว'
        ],
        watch: [
          'ตามใจตัวเองมากไป เงินรั่วโดยไม่รู้ตัว',
          'คนอายุน้อยกว่าหรือลูกน้องอาจยังไม่ทันใจ อย่าใช้อารมณ์นำ'
        ],
        example: 'วันนี้อาจมีไอเดียที่อยากลองทันที ลูกน้องมาถาม ลูกหลานเรียกหา หรือมีเงินเล็กๆ เข้าแบบพอให้ยิ้มได้ ดวงนี้ดีตรงสร้างความหวัง แต่ต้องไม่ฟุ่มเฟือย',
        level: 'neutral'
      },
      {
        name: 'อริ',
        short: 'อุปสรรค หนี้สิน ป่วย ถูกโกง',
        meaning: 'อุปสรรค นานา หนี้สิน วิตก ถูกโกง ป่วยไข้ อุบัติเหตุ ถูกจองจำ ตาย',
        oracle: 'วันนี้ดวงส่งงานแก้ งานกันพลาด และบททดสอบความอดทนมาให้',
        plain: 'อริคือคู่ต่อสู้ของความราบรื่น ไม่จำเป็นต้องเป็นศัตรูตัวเป็นๆ เสมอไป อาจมาในรูปงานเสีย เอกสารผิด หนี้ตาม สุขภาพตก คนพูดขวาง หรือเรื่องเล็กที่กินแรงกว่าที่คิด',
        do: [
          'เคลียร์งานค้าง จ่ายหนี้ จัดเอกสาร และปิดช่องผิดพลาด',
          'ดูแลสุขภาพ พักให้พอ กินยาให้ตรง และอย่าฝืนร่างกาย',
          'ทำอะไรสำคัญให้มีคนช่วยตรวจ หรืออย่างน้อยตรวจซ้ำเองอีกหนึ่งรอบ'
        ],
        watch: [
          'คนเอาเปรียบ ข้อตกลงคลุมเครือ และคำพูดที่ทำให้หัวร้อน',
          'หลีกเลี่ยงการเปิดศึกใหม่ เพราะวันนี้ชนะก็เหนื่อย'
        ],
        example: 'ถ้าเครื่องมือเสีย ลูกค้าตาม หนี้ครบกำหนด หรือร่างกายเริ่มเตือน นั่นคืออริมาเคาะประตู วันนี้ชนะดวงได้ด้วยความละเอียด ไม่ใช่ความดื้อ',
        level: 'caution'
      },
      {
        name: 'ปัตตนิ',
        short: 'คู่ครอง คู่สัญญา หุ้นส่วน',
        meaning: 'สามี - ภรรยา คู่สัญญา คู่ชู้ หุ้นส่วน คนรู้จักเก่าแก่',
        oracle: 'ดวงวันนี้ไปอยู่ตรงคนที่ยืนฝั่งตรงข้ามคุณ',
        plain: 'ปัตตนิคือคู่ทุกชนิด คู่รัก คู่ค้า ลูกค้า หุ้นส่วน คู่สัญญา หรือคนที่ต้องตกลงกันแบบหนึ่งต่อหนึ่ง วันนี้คุณจะไม่ได้เดินคนเดียว คำตอบหลายอย่างขึ้นกับว่าอีกฝ่ายรู้สึกอย่างไรและตกลงกันได้แค่ไหน',
        do: [
          'นัดคุย ปรับความเข้าใจ เจรจาเงื่อนไข หรือแบ่งหน้าที่ให้ชัด',
          'ฟังให้จบก่อนตอบ เพราะวันนี้อีกฝ่ายต้องการพื้นที่มากกว่าคำสั่ง',
          'ความสัมพันธ์ที่ดี ใช้วันนี้เติมความชัดเจน ความสัมพันธ์ที่ค้างคา ใช้วันนี้เปิดใจ'
        ],
        watch: [
          'คำพูดเพียงประโยคเดียวอาจเปลี่ยนอารมณ์ทั้งวัน',
          'ข้อตกลง คู่สัญญา หรือเอกสารร่วมกัน ต้องอ่านก่อนรับปาก'
        ],
        example: 'คนรักอาจอยากคุย ลูกค้าอาจต่อรอง หุ้นส่วนอาจขอแก้เงื่อนไข วันนี้ถ้าคุยดีจะได้ใจคน แต่ถ้าพูดแข็งเกินไป เรื่องเล็กจะกลายเป็นเรื่องคู่ทันที',
        level: 'neutral'
      },
      {
        name: 'มรณะ',
        short: 'สูญเสีย ห่างไกล ขาดทุน',
        meaning: 'ความตาย สูญเสีย ห่างไกล ว่างเปล่า ขาดทุน เสียหาย ถูกจองจำ ตาย',
        oracle: 'อย่าฝืนดวง วันนี้ต้องรู้จักชะลอและตัดไฟแต่ต้นลม',
        plain: 'มรณะไม่ใช่แปลว่าจะเกิดเรื่องร้ายเสมอไป แต่เป็นสัญญาณของการเสีย การจบ การเปลี่ยน การห่าง หรือสิ่งที่ควบคุมไม่ได้ วันนี้สิ่งสำคัญคืออย่าเพิ่มความเสี่ยงให้ชีวิตโดยไม่จำเป็น',
        do: [
          'เก็บตัว เคลียร์ของเก่า ปิดเรื่องที่ควรจบ และทำอะไรให้เรียบร้อยเงียบๆ',
          'เช็กกระเป๋า รถ เอกสาร เงิน โอนเงิน และเส้นทางก่อนออกจากบ้าน',
          'ถ้าต้องเลือก ให้เลือกทางที่เสียหายน้อยที่สุดก่อน อย่าเลือกเพราะอยากเอาชนะ'
        ],
        watch: [
          'หลีกเลี่ยงลงทุนใหญ่ เซ็นสัญญาเสี่ยง ให้ยืมเงิน หรือฝากของสำคัญไว้กับคนอื่น',
          'ของหาย รถเสีย เจ็บตัว ผิดคำพูด หรือเสียความรู้สึก เกิดง่ายกว่าวันปกติ'
        ],
        example: 'วันนี้ถ้ารู้สึกว่าอะไรไม่แน่ ให้เชื่อสัญชาตญาณไว้ก่อน เลื่อนเรื่องเสี่ยงได้ก็เลื่อน ตรวจซ้ำได้ก็ตรวจ เพราะมรณะสอนให้รอดด้วยความไม่ประมาท',
        level: 'caution'
      },
      {
        name: 'ศุภะ',
        short: 'ความเจริญรุ่งเรือง',
        meaning: 'ความเจริญรุ่งเรืองส่วนตัว ทั้งในบ้านและที่ทำงาน',
        oracle: 'ประตูสูงเปิด คนใหญ่ คนดี หรือโอกาสดีอาจเข้ามาช่วย',
        plain: 'ศุภะคือจังหวะที่ชีวิตมองไกลขึ้น เหมาะกับเรื่องบุญ ผู้ใหญ่ ครู ความรู้ การเดินทางไกล การขออนุมัติ และสิ่งที่ทำแล้วพาคุณสูงขึ้นกว่าเดิม วันนี้ดวงมีแรงหนุนมากกว่าวันอื่น',
        do: [
          'เข้าหาผู้ใหญ่ ครู หัวหน้า หรือคนที่มีอำนาจช่วยเปิดทาง',
          'ทำบุญ ไหว้พระ เรียนรู้ เดินทาง หรือขยับแผนที่เกี่ยวกับอนาคต',
          'ขออนุมัติ เสนอเรื่องสำคัญ หรือเริ่มสิ่งที่อยากให้เติบโต'
        ],
        watch: [
          'อย่าดีใจจนรับปากใหญ่เกินกำลัง',
          'โอกาสดีต้องมีการเตรียมตัว ไม่ใช่รอให้โชคทำงานแทนทั้งหมด'
        ],
        example: 'ถ้าจะขอคำแนะนำ ขออนุมัติ สมัครเรียน เดินทางไกล หรือเริ่มเรื่องที่ต้องการแรงสนับสนุน วันนี้ใช้ได้ดี ดวงเหมือนมีคนเปิดประตูให้ แต่คุณยังต้องเป็นคนก้าวเข้าไปเอง',
        level: 'good'
      },
      {
        name: 'กัมมะ',
        short: 'งาน การติดต่อ การจัดการ',
        meaning: 'งานที่ติดต่อ บริหารจัดการ ในครัวเรือน และนอกบ้าน',
        oracle: 'เวทีของวันนี้คือหน้าที่ งาน และสิ่งที่คนอื่นมองเห็นจากผลงานคุณ',
        plain: 'กัมมะคือเรือนการงาน ความรับผิดชอบ เจ้านาย ลูกค้า ชื่อเสียง และการจัดการ วันนี้เรื่องส่วนตัวอาจต้องหลบให้เรื่องงานก่อน เพราะสิ่งที่คุณทำจะถูกนับ ถูกมอง หรือถูกถามผลลัพธ์',
        do: [
          'ประชุม ส่งงาน วางแผน จัดตาราง หรือคุยเรื่องหน้าที่ให้ชัด',
          'แสดงความรับผิดชอบให้เห็นเป็นรูปธรรม ไม่ใช่แค่พูดว่าจะทำ',
          'งานที่ต้องการความเป็นมืออาชีพ เหมาะกับวันนี้มาก'
        ],
        watch: [
          'รับปากหลายทางแล้วชนกันเอง',
          'อารมณ์ในที่ทำงานกระทบภาพลักษณ์เร็ว อย่าเผลอพูดแรงเพราะเหนื่อย'
        ],
        example: 'วันนี้ถ้ามีคนถามงาน ตามงาน เรียกประชุม หรือรอดูผลลัพธ์ อย่าหนีเวที จัดลำดับให้ดีแล้วเดินทีละเรื่อง กัมมะให้แต้มกับคนที่รับผิดชอบจริง',
        level: 'neutral'
      },
      {
        name: 'ลาภะ',
        short: 'โชคลาภ ลาภผล',
        meaning: 'โชคลาภ ลาภผลที่ได้รับมา จะมีจะหมดว่ากันไป',
        oracle: 'แรงหนุนจากคนรอบวง โอกาส และผลที่รออยู่เริ่มขยับเข้ามา',
        plain: 'ลาภะคือสิ่งที่ได้เพิ่ม ได้ต่อ ได้จากคน ได้จากกลุ่ม ได้จากโอกาส ไม่จำเป็นต้องเป็นเงินก้อนเสมอไป อาจเป็นลูกค้าเก่า คนแนะนำ ข่าวดี ของฝาก หรือช่องทางที่ทำให้ความหวังเริ่มมีรูป',
        do: [
          'ติดต่อเพื่อน กลุ่มลูกค้า เครือข่าย หรือคนที่เคยช่วยเหลือกัน',
          'ประกาศงาน แชร์ผลงาน ขอความร่วมมือ หรือเปิดรับโอกาสเสริม',
          'ถ้ามีลาภเข้ามา ให้แยกเก็บไว้บางส่วน อย่าใช้หมดตามอารมณ์'
        ],
        watch: [
          'คำชวนที่ฟังดีเกินไปต้องดูเงื่อนไขซ่อนอยู่',
          'เพื่อนหรือคนรู้จักอาจพาโอกาสมา แต่คุณต้องคัดกรองเอง'
        ],
        example: 'วันนี้อาจมีคนทักมาพร้อมงาน ลูกค้าเก่ากลับมา เพื่อนแนะนำช่องทาง หรือมีรายได้พิเศษเล็กๆ ลาภะให้โอกาส แต่ไม่ควรโลภจนลืมดูความจริง',
        level: 'good'
      },
      {
        name: 'วินาศ',
        short: 'สูญเสีย เหนื่อยล้า วิตก',
        meaning: 'ความสูญเสีย เหนื่อยล้า วิตกกังวล ว่างเปล่า ขาดทุน ถูกจองจำ ตาย',
        oracle: 'เรื่องหลังฉาก ความลับ และความเหนื่อยลึกๆ จะดังขึ้นกว่าปกติ',
        plain: 'วินาศคือสิ่งที่ไม่ออกหน้าแต่กินใจ กินเงิน กินเวลา หรือกินแรง อาจเป็นความลับ ค่าใช้จ่ายแฝง งานที่ไม่มีคนเห็น ความคิดมาก หรือเรื่องของคนอื่นที่เผลอรับมาเป็นภาระ',
        do: [
          'ทำงานเงียบๆ เก็บรายละเอียด เคลียร์เรื่องหลังบ้าน หรือพักใจให้พอ',
          'ตรวจรหัสผ่าน เอกสาร ของสำคัญ ค่าใช้จ่ายแฝง และเรื่องส่วนตัว',
          'ถอยออกจากเรื่องปะทะ ทำบุญ นั่งนิ่งๆ หรืออยู่กับตัวเองจะช่วยลดแรงเสีย'
        ],
        watch: [
          'ไม่ควรเปิดศึก เปิดตัวเรื่องใหญ่ หรือเล่าความลับให้คนที่ยังไม่แน่ใจ',
          'เงินรั่ว นอนไม่พอ คิดมาก หรือถูกดึงไปยุ่งเรื่องคนอื่นเกิดง่าย'
        ],
        example: 'ถ้าวันนี้รู้สึกเหนื่อยทั้งที่ยังไม่ได้ทำอะไรมาก หรือมีเรื่องลับ เรื่องเสียเงินเล็กๆ เรื่องที่พูดไม่ได้เข้ามา นั่นคือวินาศทำงาน ทางรอดคือเงียบ รอบคอบ และไม่รับภาระที่ไม่ใช่ของตัวเอง',
        level: 'caution'
      }
    ];

const OWNER_BIRTH_AGE_OPTIONS = {
  showOppositeHouse: true,
  showHouseMeaning: true,
  showAdvice: true,
  showOracle: true,
  showExample: true
};

function calculateOwnerAge(input) {
  const payload = normalizeOwnerAgeInput_(input);
  if (payload.error) return payload;

  let result;
  if (payload.mode === 'month') {
    result = buildOwnerMonthly_(payload.birthDay, payload.birthMonth, payload.targetMonth, payload.beYear);
  } else if (payload.mode === 'monthYear') {
    result = buildOwnerAnnualMonths_(payload.birthDay, payload.birthMonth, payload.beYear);
  } else if (payload.mode === 'yearBirth') {
    result = buildOwnerAnnualBirth_(payload.birthDay, payload.birthMonth, payload.birthYear, payload.beYear);
  } else {
    result = buildOwnerAnnual_(payload.birthDay, payload.birthMonth, payload.beYear);
  }

  if (result.error) return result;

  return {
    ok: true,
    inputs: payload,
    months: OWNER_AGE_MONTHS,
    summary: result.summary,
    counts: countOwnerAgeLevels_(result.items),
    items: result.items,
    todayKey: ownerAgeDateKey_(new Date())
  };
}

function calculateOwnerAgeToday(input) {
  const base = normalizeOwnerAgeInput_(input);
  if (base.error) return base;

  const today = ownerAgeStartOfDay_(new Date());
  const periodStart = ownerAgePeriodStartForDate_(today, base.birthDay);
  const baseYear = ownerAgeAnnualBaseYearForDate_(today, base.birthMonth, base.birthDay);
  const annualMode = ['monthYear', 'year', 'yearBirth'].indexOf(base.mode) >= 0;

  const nextInput = {
    birthDay: base.birthDay,
    birthMonth: base.birthMonth,
    birthYear: base.birthYear,
    targetMonth: periodStart.getMonth(),
    beYear: (annualMode ? baseYear : periodStart.getFullYear()) + 543,
    mode: base.mode
  };

  const result = calculateOwnerAge(nextInput);
  result.today = {
    targetMonth: nextInput.targetMonth,
    beYear: nextInput.beYear,
    key: ownerAgeDateKey_(today)
  };
  return result;
}

function calculateOwnerBirthAge(input) {
  const payload = normalizeOwnerBirthAgeInput_(input);
  if (payload.error) return payload;

  const elapsedDays = Math.round((payload.targetDate.getTime() - payload.birthDate.getTime()) / 86400000);
  if (elapsedDays < 0) {
    return {
      ok: false,
      code: 'TARGET_BEFORE_BIRTH',
      message: 'วันที่ดูต้องไม่ก่อนวันเกิด'
    };
  }

  const houseIndex = elapsedDays % OWNER_AGE_HOUSES.length;
  const oppositeIndex = (houseIndex + 6) % OWNER_AGE_HOUSES.length;
  const house = OWNER_AGE_HOUSES[houseIndex];
  const opposite = OWNER_AGE_HOUSES[oppositeIndex];
  const item = {
    key: ownerAgeDateKey_(payload.targetDate),
    date: payload.targetDate.toISOString(),
    order: elapsedDays,
    periodKey: ownerAgeDateKey_(payload.birthDate),
    elapsedDays: elapsedDays,
    birthDateKey: ownerAgeDateKey_(payload.birthDate),
    birthDateLabel: ownerAgeFormatDate_(payload.birthDate, true, true),
    targetDateLabel: ownerAgeFormatDate_(payload.targetDate, true, true),
    isBirthAge: true,
    house: ownerAgeHousePayload_(house, houseIndex),
    opposite: ownerAgeHousePayload_(opposite, oppositeIndex)
  };

  return {
    ok: true,
    mode: 'birth',
    inputs: payload.normalized,
    months: OWNER_AGE_MONTHS,
    summary: item.birthDateLabel + ' ถึง ' + item.targetDateLabel + ' · นับได้ ' + elapsedDays + ' วัน',
    counts: countOwnerAgeLevels_([item]),
    items: [item],
    item: item,
    pairLabel: house.name + ' -> ' + opposite.name,
    displayOptions: OWNER_BIRTH_AGE_OPTIONS,
    todayKey: ownerAgeDateKey_(new Date())
  };
}

function calculateOwnerBirthAgeToday(input) {
  const today = ownerAgeStartOfDay_(new Date());
  const source = input || {};
  const nextInput = {
    birthDay: source.birthDay,
    birthMonth: source.birthMonth,
    birthYear: source.birthYear,
    targetDay: today.getDate(),
    targetMonth: today.getMonth(),
    targetYear: today.getFullYear() + 543
  };
  const result = calculateOwnerBirthAge(nextInput);
  if (result && result.ok) {
    result.today = {
      targetDay: nextInput.targetDay,
      targetMonth: nextInput.targetMonth,
      targetYear: nextInput.targetYear,
      key: ownerAgeDateKey_(today)
    };
  }
  return result;
}

function normalizeOwnerAgeInput_(input) {
  const source = input || {};
  const birthDay = ownerAgeClampInt_(source.birthDay, 1, 31, 29);
  const birthMonth = ownerAgeClampInt_(source.birthMonth, 0, 11, 0);
  const targetMonth = ownerAgeClampInt_(source.targetMonth, 0, 11, birthMonth);
  const beYear = ownerAgeClampInt_(source.beYear, 1, 3000, new Date().getFullYear() + 543);
  const birthYear = ownerAgeClampInt_(source.birthYear, 1, 3000, 2488);
  const mode = ['month', 'monthYear', 'year', 'yearBirth'].indexOf(source.mode) >= 0 ? source.mode : 'month';

  return {
    birthDay: birthDay,
    birthMonth: birthMonth,
    birthYear: birthYear,
    targetMonth: targetMonth,
    beYear: beYear,
    adYear: beYear - 543,
    mode: mode
  };
}

function normalizeOwnerBirthAgeInput_(input) {
  const source = input || {};
  const now = ownerAgeStartOfDay_(new Date());
  const birthYear = ownerAgeClampInt_(source.birthYear, 1, 3000, 2488);
  const birthMonth = ownerAgeClampInt_(source.birthMonth, 0, 11, 6);
  const targetYear = ownerAgeClampInt_(source.targetYear, 1, 3000, now.getFullYear() + 543);
  const targetMonth = ownerAgeClampInt_(source.targetMonth, 0, 11, now.getMonth());
  const birthDay = ownerAgeClampInt_(source.birthDay, 1, 31, 29);
  const targetDay = ownerAgeClampInt_(source.targetDay, 1, 31, now.getDate());
  const birthDate = buildOwnerBirthAgeDate_(birthYear, birthMonth, birthDay);
  const targetDate = buildOwnerBirthAgeDate_(targetYear, targetMonth, targetDay);

  return {
    birthDate: birthDate,
    targetDate: targetDate,
    normalized: {
      birthDay: birthDate.getDate(),
      birthMonth: birthDate.getMonth(),
      birthYear: birthDate.getFullYear() + 543,
      targetDay: targetDate.getDate(),
      targetMonth: targetDate.getMonth(),
      targetYear: targetDate.getFullYear() + 543
    }
  };
}

function buildOwnerBirthAgeDate_(beYear, monthIndex, day) {
  const adYear = beYear - 543;
  const safeDay = Math.min(day, ownerAgeDaysInMonth_(adYear, monthIndex));
  return ownerAgeStartOfDay_(new Date(adYear, monthIndex, safeDay));
}

function buildOwnerMonthly_(birthDay, birthMonth, targetMonth, beYear) {
  const adYear = beYear - 543;
  const startYear = adYear;
  const start = ownerAgeCycleStartForMonth_(startYear, targetMonth, birthDay);
  const nextMonth = targetMonth === 11 ? 0 : targetMonth + 1;
  const nextYear = targetMonth === 11 ? startYear + 1 : startYear;
  const end = ownerAgeCycleStartForMonth_(nextYear, nextMonth, birthDay);
  
  const items = [];
  let index = 0;
  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const houseIndex = index % OWNER_AGE_HOUSES.length;
    const house = OWNER_AGE_HOUSES[houseIndex];
    const d = new Date(cursor);
    items.push({
      key: ownerAgeDateKey_(d),
      date: d.toISOString(),
      order: index,
      periodKey: ownerAgeDateKey_(d),
      house: ownerAgeHousePayload_(house, houseIndex)
    });
    index++;
  }

  const endDisplay = new Date(end.getTime() - 86400000);
  return {
    items: items,
    summary: ownerAgeFormatDate_(start, true) + ' ถึง ' + ownerAgeFormatDate_(endDisplay, true)
  };
}

function buildOwnerAnnual_(birthDay, birthMonth, beYear) {
  const adYear = beYear - 543;
  const start = ownerAgeCycleStartForMonth_(adYear, birthMonth, birthDay);
  const end = ownerAgeCycleStartForMonth_(adYear + 1, birthMonth, birthDay);
  const items = [];

  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const itemDate = new Date(cursor);
    const periodStart = ownerAgePeriodStartForDate_(itemDate, birthDay);
    const offset = Math.round((itemDate.getTime() - periodStart.getTime()) / 86400000);
    const houseIndex = offset % OWNER_AGE_HOUSES.length;
    const house = OWNER_AGE_HOUSES[houseIndex];
    items.push({
      key: ownerAgeDateKey_(cursor),
      date: itemDate.toISOString(),
      order: offset,
      periodKey: ownerAgeDateKey_(periodStart),
      house: ownerAgeHousePayload_(house, houseIndex)
    });
  }

  const endDisplay = new Date(end.getTime() - 86400000);
  return {
    items: items,
    summary: ownerAgeFormatDate_(start, true) + ' ถึง ' + ownerAgeFormatDate_(endDisplay, true)
  };
}

function buildOwnerAnnualMonths_(birthDay, birthMonth, beYear) {
  const annual = buildOwnerAnnual_(birthDay, birthMonth, beYear);
  if (annual.error) return annual;

  const starts = annual.items.filter(function(item) {
    return item.order === 0;
  }).slice(0, 12);

  const items = starts.map(function(startItem, index) {
    const nextStart = starts[index + 1];
    const endKey = nextStart ? ownerAgePreviousDateKey_(nextStart.key) : annual.items[annual.items.length - 1].key;
    const houseIndex = index % OWNER_AGE_HOUSES.length;
    const house = OWNER_AGE_HOUSES[houseIndex];
    return {
      key: startItem.key,
      date: startItem.key,
      endDate: endKey,
      order: index,
      periodKey: startItem.periodKey || startItem.key,
      isPeriod: true,
      house: ownerAgeHousePayload_(house, houseIndex)
    };
  });

  return {
    items: items,
    summary: ownerAgeFormatDate_(starts[0].key, true) + ' ถึง ' + ownerAgeFormatDate_(items[items.length - 1].endDate, true)
  };
}

function buildOwnerAnnualBirth_(birthDay, birthMonth, birthYear, beYear) {
  const adYear = beYear - 543;
  const start = ownerAgeCycleStartForMonth_(adYear, birthMonth, birthDay);
  const end = ownerAgeCycleStartForMonth_(adYear + 1, birthMonth, birthDay);
  const birthAnchor = buildOwnerBirthAgeDate_(birthYear, birthMonth, birthDay);
  if (start.getTime() < birthAnchor.getTime()) {
    return {
      ok: false,
      error: true,
      code: 'YEAR_BEFORE_BIRTH',
      message: 'ปีที่ดูต้องไม่ก่อนปีเกิดจริง'
    };
  }
  const items = [];

  for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) {
    const itemDate = new Date(cursor);
    const periodStart = ownerAgePeriodStartForDate_(itemDate, birthDay);
    const offset = Math.round((itemDate.getTime() - periodStart.getTime()) / 86400000);
    const elapsedDays = Math.round((itemDate.getTime() - birthAnchor.getTime()) / 86400000);
    const houseIndex = elapsedDays % OWNER_AGE_HOUSES.length;
    const house = OWNER_AGE_HOUSES[houseIndex];
    items.push({
      key: ownerAgeDateKey_(cursor),
      date: itemDate.toISOString(),
      order: offset,
      periodKey: ownerAgeDateKey_(periodStart),
      elapsedDays: elapsedDays,
      birthDateKey: ownerAgeDateKey_(birthAnchor),
      house: ownerAgeHousePayload_(house, houseIndex)
    });
  }

  const endDisplay = new Date(end.getTime() - 86400000);
  return {
    items: items,
    summary: ownerAgeFormatDate_(start, true) + ' ถึง ' + ownerAgeFormatDate_(endDisplay, true)
  };
}

function countOwnerAgeLevels_(items) {
  return items.reduce(function(acc, item) {
    const level = item.house.level;
    acc.all++;
    acc[level] = (acc[level] || 0) + 1;
    return acc;
  }, { all: 0, good: 0, neutral: 0, caution: 0 });
}

function ownerAgeHousePayload_(house, houseIndex) {
  const opposite = OWNER_AGE_HOUSES[(houseIndex + 6) % OWNER_AGE_HOUSES.length];
  return {
    name: house.name,
    short: house.short,
    meaning: house.meaning,
    oracle: house.oracle,
    plain: house.plain,
    do: house.do || [],
    watch: house.watch || [],
    example: house.example,
    level: house.level,
    oppositeName: opposite.name
  };
}

function ownerAgeCycleStartForMonth_(adYear, monthIndex, day) {
  return new Date(adYear, monthIndex, Math.min(day, ownerAgeDaysInMonth_(adYear, monthIndex)));
}

function ownerAgePreviousMonthParts_(adYear, monthIndex) {
  return monthIndex === 0
    ? { year: adYear - 1, month: 11 }
    : { year: adYear, month: monthIndex - 1 };
}

function ownerAgeCycleStartForOffset_(adYear, birthMonth, birthDay, offset) {
  const absoluteMonth = birthMonth + offset;
  const year = adYear + Math.floor(absoluteMonth / 12);
  const month = ((absoluteMonth % 12) + 12) % 12;
  return ownerAgeCycleStartForMonth_(year, month, birthDay);
}

function ownerAgeAnnualPeriodStarts_(adYear, birthMonth, birthDay) {
  const starts = [];
  for (let index = 0; index < 13; index++) {
    starts.push(ownerAgeCycleStartForOffset_(adYear, birthMonth, birthDay, index));
  }
  return starts;
}

function ownerAgeCycleYearForMonth_(adYear, birthMonth, targetMonth) {
  return targetMonth < birthMonth ? adYear + 1 : adYear;
}

function ownerAgeAnnualBaseYearForDate_(date, birthMonth, birthDay) {
  const startThisYear = ownerAgeCycleStartForMonth_(date.getFullYear(), birthMonth, birthDay);
  return date < startThisYear ? date.getFullYear() - 1 : date.getFullYear();
}

function ownerAgePeriodStartForDate_(date, birthDay) {
  let start = ownerAgeCycleStartForMonth_(date.getFullYear(), date.getMonth(), birthDay);
  if (date < start) {
    const previous = ownerAgePreviousMonthParts_(date.getFullYear(), date.getMonth());
    start = ownerAgeCycleStartForMonth_(previous.year, previous.month, birthDay);
  }
  return start;
}

function ownerAgeDaysInMonth_(adYear, monthIndex) {
  return new Date(adYear, monthIndex + 1, 0).getDate();
}

function ownerAgeStartOfDay_(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function ownerAgeDateKey_(date) {
  if (typeof date === 'string') date = new Date(date);
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return y + '-' + m + '-' + d;
}

function ownerAgeDateFromKey_(key) {
  const parts = String(key || '').split('-').map(function(part) {
    return Number(part);
  });
  if (parts.length !== 3 || parts.some(function(part) { return !Number.isFinite(part); })) {
    return ownerAgeStartOfDay_(new Date());
  }
  return new Date(parts[0], parts[1] - 1, parts[2]);
}

function ownerAgePreviousDateKey_(key) {
  const date = ownerAgeDateFromKey_(key);
  date.setDate(date.getDate() - 1);
  return ownerAgeDateKey_(date);
}

function ownerAgeFormatDate_(date, includeYear, includeDayName) {
  if (typeof date === 'string') date = ownerAgeDateFromKey_(date);
  const base = date.getDate() + ' ' + OWNER_AGE_MONTHS[date.getMonth()].short;
  const formatted = includeYear ? base + ' ' + (date.getFullYear() + 543) : base;
  if (includeDayName) {
    const DAY_NAMES = ['วันอาทิตย์', 'วันจันทร์', 'วันอังคาร', 'วันพุธ', 'วันพฤหัสบดี', 'วันศุกร์', 'วันเสาร์'];
    return DAY_NAMES[date.getDay()] + ' ' + formatted;
  }
  return formatted;
}

function ownerAgeClampInt_(value, min, max, fallback) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.min(max, Math.max(min, Math.trunc(number)));
}

return { calculateOwnerAge: calculateOwnerAge, calculateOwnerAgeToday: calculateOwnerAgeToday, calculateOwnerBirthAge: calculateOwnerBirthAge, calculateOwnerBirthAgeToday: calculateOwnerBirthAgeToday };
})();

  const serviceMap = {
    getZodiacWheelData: () => ZodiacService.getZodiacWheelData(),
    calculateZodiacWheel: (payload) => ZodiacService.calculateZodiacWheel(payload),
    getDailyData: (payload) => DailyService.getDailyData(payload),
    calculateAge: (payload) => AgeYearService.calculateAge(payload),
    calculateAgeToday: (payload) => AgeYearService.calculateAgeToday(payload),
    calculateBirthAge: (payload) => AgeYearService.calculateBirthAge(payload),
    calculateBirthAgeToday: (payload) => AgeYearService.calculateBirthAgeToday(payload),
    calculateAgeMonth: (payload) => AgeMonthService.calculateAgeMonth(payload),
    calculateAgeMonthToday: (payload) => AgeMonthService.calculateAgeMonthToday(payload),
    calculateOwnerAge: (payload) => OwnerAgeService.calculateOwnerAge(payload),
    calculateOwnerAgeToday: (payload) => OwnerAgeService.calculateOwnerAgeToday(payload),
    calculateOwnerBirthAge: (payload) => OwnerAgeService.calculateOwnerBirthAge(payload),
    calculateOwnerBirthAgeToday: (payload) => OwnerAgeService.calculateOwnerBirthAgeToday(payload)
  };

  function makeRunner(successHandler, failureHandler) {
    const runner = {};
    runner.withSuccessHandler = (handler) => makeRunner(handler, failureHandler);
    runner.withFailureHandler = (handler) => makeRunner(successHandler, handler);

    Object.keys(serviceMap).forEach((functionName) => {
      runner[functionName] = (payload) => {
        window.setTimeout(() => {
          try {
            const result = serviceMap[functionName](payload || {});
            if (typeof successHandler === 'function') successHandler(result);
          } catch (error) {
            if (typeof failureHandler === 'function') failureHandler(error);
            else console.error(error);
          }
        }, 0);
        return runner;
      };
    });

    return runner;
  }

  window.OFFLINE_RUNNER = makeRunner(null, null);
})();
